import {supabase} from '../lib/supabase';
import type {BalanceSheet,BalanceSnapshot,DashboardSummary,PageResult,PageState,PnlReport,Role} from './types';

const range=(p:PageState)=>[(p.page-1)*p.pageSize,p.page*p.pageSize-1] as const;
const term=(v:string)=>v.trim().replace(/[,%()]/g,' ');
function applyDate(q:any,col:string,p:PageState){if(p.from)q=q.gte(col,p.from);if(p.to)q=q.lte(col,p.to);return q}
function finish(q:any,p:PageState){const[a,b]=range(p);return q.order(p.sort,{ascending:p.ascending}).range(a,b)}
function exportFinish(q:any,p:PageState){return q.order(p.sort,{ascending:p.ascending}).range(0,9999)}
function fail(error:any){if(error)throw new Error(error.message||'Request failed')}
function saved<T>(data:T|null):T{if(!data)throw new Error('The server did not return the saved record. Please retry.');return data}

export async function dashboardSummary(start:string,end:string){const{data,error}=await supabase.rpc('get_dashboard_summary',{p_start:start,p_end:end});fail(error);const d=data as DashboardSummary;if(d&&d.payables===undefined){const{data:rows,error:e}=await supabase.from('transactions').select('amount,paid_amount').eq('direction','expense').is('archived_at',null).gte('transaction_date',start).lte('transaction_date',end);fail(e);d.payables=(rows||[]).reduce((s:any,r:any)=>s+Math.max(0,Number(r.amount||0)-Number(r.paid_amount||0)),0)}return d}
export async function pnlReport(start:string,end:string,prevStart:string,prevEnd:string){const{data,error}=await supabase.rpc('get_pnl_report',{p_start:start,p_end:end,p_prev_start:prevStart,p_prev_end:prevEnd});fail(error);return data as PnlReport}

function deliveriesQuery(p:PageState,count=false){let q:any=supabase.from('deliveries').select('id,delivery_number,delivery_date,customer_id,driver_id,vehicle_id,source_type,from_location,to_location,description,status,expected_income,payment_status,notes,delivered_at,customers(name,email,phone,address),vehicles(registration_number),profiles!deliveries_driver_id_fkey(full_name)',count?{count:'exact'}:undefined).is('archived_at',null);q=applyDate(q,'delivery_date',p);if(p.search){const s=term(p.search);q=q.or(`delivery_number.ilike.%${s}%,from_location.ilike.%${s}%,to_location.ilike.%${s}%,description.ilike.%${s}%`)}return q}
export async function deliveriesPage(p:PageState):Promise<PageResult<any>>{const{data,error,count}=await finish(deliveriesQuery(p,true),p);fail(error);return{rows:data||[],count:count||0}}
export async function deliveriesExport(p:PageState){const{data,error}=await exportFinish(deliveriesQuery(p),p);fail(error);return data||[]}

function transactionsQuery(p:PageState,direction:'income'|'expense',includeIds?:string[],excludeIds?:string[],count=false){let q:any=supabase.from('transactions').select('id,transaction_number,transaction_date,direction,category_id,amount,paid_amount,delivery_id,vehicle_id,driver_id,customer_id,vendor_id,description,payment_status,payment_method,source,needs_review,transaction_categories(name,code),customers(name),vendors(name),vehicles(registration_number)',count?{count:'exact'}:undefined).is('archived_at',null).eq('direction',direction);if(includeIds?.length)q=q.in('category_id',includeIds);if(excludeIds?.length)q=q.not('category_id','in',`(${excludeIds.join(',')})`);if(p.categoryId)q=q.eq('category_id',p.categoryId);q=applyDate(q,'transaction_date',p);if(p.search){const s=term(p.search);q=q.or(`transaction_number.ilike.%${s}%,description.ilike.%${s}%`)}return q}
export async function transactionsPage(p:PageState,direction:'income'|'expense',includeIds?:string[],excludeIds?:string[]):Promise<PageResult<any>>{const{data,error,count}=await finish(transactionsQuery(p,direction,includeIds,excludeIds,true),p);fail(error);return{rows:data||[],count:count||0}}
export async function transactionsExport(p:PageState,direction:'income'|'expense',includeIds?:string[],excludeIds?:string[]){const{data,error}=await exportFinish(transactionsQuery(p,direction,includeIds,excludeIds),p);fail(error);return data||[]}

function fuelQuery(p:PageState,count=false){let q:any=supabase.from('fuel_logs').select('id,transaction_id,vehicle_id,driver_id,delivery_id,fuel_date,litres,amount,odometer,station,notes,vehicles(registration_number),profiles!fuel_logs_driver_id_fkey(full_name)',count?{count:'exact'}:undefined).is('archived_at',null);q=applyDate(q,'fuel_date',p);if(p.search){const s=term(p.search);q=q.or(`station.ilike.%${s}%,notes.ilike.%${s}%`)}return q}
export async function fuelPage(p:PageState):Promise<PageResult<any>>{const{data,error,count}=await finish(fuelQuery(p,true),p);fail(error);return{rows:data||[],count:count||0}}
export async function fuelExport(p:PageState){const{data,error}=await exportFinish(fuelQuery(p),p);fail(error);return data||[]}

function maintenanceQuery(p:PageState,count=false){let q:any=supabase.from('maintenance_records').select('id,transaction_id,vehicle_id,maintenance_date,maintenance_type,odometer,description,vendor_id,cost,next_service_date,next_service_odometer,status,vehicles(registration_number),vendors(name)',count?{count:'exact'}:undefined).is('archived_at',null);q=applyDate(q,'maintenance_date',p);if(p.search){const s=term(p.search);q=q.or(`maintenance_type.ilike.%${s}%,description.ilike.%${s}%`)}return q}
export async function maintenancePage(p:PageState):Promise<PageResult<any>>{const{data,error,count}=await finish(maintenanceQuery(p,true),p);fail(error);return{rows:data||[],count:count||0}}
export async function maintenanceExport(p:PageState){const{data,error}=await exportFinish(maintenanceQuery(p),p);fail(error);return data||[]}

function vehiclesQuery(p:PageState,count=false){let q:any=supabase.from('vehicles').select('id,registration_number,make,model,year,current_odometer,status,notes',count?{count:'exact'}:undefined).is('archived_at',null);if(p.search){const s=term(p.search);q=q.or(`registration_number.ilike.%${s}%,make.ilike.%${s}%,model.ilike.%${s}%`)}return q}
export async function vehiclesPage(p:PageState):Promise<PageResult<any>>{const{data,error,count}=await finish(vehiclesQuery(p,true),p);fail(error);return{rows:data||[],count:count||0}}
export async function vehiclesExport(p:PageState){const{data,error}=await exportFinish(vehiclesQuery(p),p);fail(error);return data||[]}

export async function masters(role?:Role){const isDriver=role==='driver';const requests:any[]=[supabase.from('transaction_categories').select('id,code,name,direction,active,system').order('direction').order('name'),supabase.from('customers').select('id,name,phone,email,address,active').eq('active',true).order('name'),supabase.from('vehicles').select('id,registration_number,make,model,status').is('archived_at',null).order('registration_number'),supabase.from('profiles').select('id,full_name,phone,role,active').eq('active',true).order('full_name'),supabase.from('app_settings').select('value').eq('key','company').maybeSingle()];if(!isDriver)requests.splice(2,0,supabase.from('vendors').select('id,name,phone,email,address,active').eq('active',true).order('name'));const results=await Promise.all(requests);for(const r of results)fail(r.error);if(isDriver){const[cats,customers,vehicles,profiles,company]=results;return{categories:cats.data||[],customers:customers.data||[],vendors:[],vehicles:vehicles.data||[],profiles:profiles.data||[],company:company.data?.value||{}}}const[cats,customers,vendors,vehicles,profiles,company]=results;return{categories:cats.data||[],customers:customers.data||[],vendors:vendors.data||[],vehicles:vehicles.data||[],profiles:profiles.data||[],company:company.data?.value||{}}}

export async function balanceSheet(asOf:string):Promise<BalanceSheet>{const[tx,snap]=await Promise.all([supabase.from('transactions').select('direction,amount,paid_amount').is('archived_at',null).lte('transaction_date',asOf),supabase.from('app_settings').select('value').eq('key','balance_sheet_snapshots').maybeSingle()]);fail(tx.error);fail(snap.error);let receivables=0,payables=0;for(const r of tx.data||[]){const due=Math.max(0,Number(r.amount||0)-Number(r.paid_amount||0));if(r.direction==='income')receivables+=due;else if(r.direction==='expense')payables+=due}const snapshots=((snap.data?.value as any)?.snapshots||[]) as BalanceSnapshot[];const snapshot=snapshots.filter(s=>s.date<=asOf).sort((a,b)=>b.date.localeCompare(a.date))[0];const s=snapshot||{date:asOf,cash_bank:0,other_current_assets:0,vehicle_book_value:0,other_noncurrent_assets:0,loans:0,other_liabilities:0,capital:0};const assets=[{name:'Cash & bank',amount:Number(s.cash_bank||0)},{name:'Accounts receivable',amount:receivables},{name:'Other current assets',amount:Number(s.other_current_assets||0)},{name:'Vehicle / equipment book value',amount:Number(s.vehicle_book_value||0)},{name:'Other non-current assets',amount:Number(s.other_noncurrent_assets||0)}];const liabilities=[{name:'Accounts payable',amount:payables},{name:'Loans',amount:Number(s.loans||0)},{name:'Other liabilities',amount:Number(s.other_liabilities||0)}];const totalAssets=assets.reduce((a,x)=>a+x.amount,0),totalLiabilities=liabilities.reduce((a,x)=>a+x.amount,0),capital=Number(s.capital||0),retained=totalAssets-totalLiabilities-capital;const equity=[{name:'Capital / owner funds',amount:capital},{name:'Retained earnings / balancing equity',amount:retained}],totalEquity=equity.reduce((a,x)=>a+x.amount,0);return{asOf,snapshot,receivables,payables,assets,liabilities,equity,totalAssets,totalLiabilities,totalEquity,netAssets:totalAssets-totalLiabilities}}

export async function saveDelivery(payload:any,id?:string){const q=id?supabase.from('deliveries').update(payload).eq('id',id):supabase.from('deliveries').insert(payload);const{data,error}=await q.select('id,delivery_number').single();fail(error);return saved(data)}
export async function saveTransaction(payload:any,id?:string){const q=id?supabase.from('transactions').update(payload).eq('id',id):supabase.from('transactions').insert(payload);const{data,error}=await q.select('id,transaction_number').single();fail(error);return saved(data)}
export async function saveFuel(payload:any,id?:string){const q=id?supabase.from('fuel_logs').update(payload).eq('id',id):supabase.from('fuel_logs').insert(payload);const{data,error}=await q.select('id').single();fail(error);return saved(data)}
export async function saveMaintenance(payload:any,id?:string){const q=id?supabase.from('maintenance_records').update(payload).eq('id',id):supabase.from('maintenance_records').insert(payload);const{data,error}=await q.select('id').single();fail(error);return saved(data)}
export async function saveVehicle(payload:any,id?:string){const q=id?supabase.from('vehicles').update(payload).eq('id',id):supabase.from('vehicles').insert(payload);const{data,error}=await q.select('id,registration_number').single();fail(error);return saved(data)}
export async function archiveRecord(table:string,id:string,userId:string){const{error}=await supabase.from(table).update({archived_at:new Date().toISOString(),archived_by:userId}).eq('id',id);fail(error)}
export async function createMaster(kind:'customer'|'vendor'|'vehicle',payload:any){const table=kind==='customer'?'customers':kind==='vendor'?'vendors':'vehicles';const{data,error}=await supabase.from(table).insert(payload).select('*').single();fail(error);return saved(data)}
export async function mergeVehicles(target:string,sources:string[]){const{data,error}=await supabase.rpc('merge_vehicles',{p_target:target,p_sources:sources});fail(error);return data}
export async function uploadDocuments(entityType:string,entityId:string,files:File[],userId:string){for(const file of files){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${userId}/${entityType}/${entityId}/${Date.now()}-${safe}`;const up=await supabase.storage.from('truck-documents').upload(path,file,{contentType:file.type||'application/octet-stream'});fail(up.error);const ins=await supabase.from('documents').insert({entity_type:entityType,entity_id:entityId,bucket:'truck-documents',path,original_name:file.name,mime_type:file.type||null,size_bytes:file.size,uploaded_by:userId});fail(ins.error)}}
export async function documentsFor(entityType:string,entityId:string){const{data,error}=await supabase.from('documents').select('id,original_name,mime_type,size_bytes,bucket,path,created_at').eq('entity_type',entityType).eq('entity_id',entityId).order('created_at',{ascending:false});fail(error);return data||[]}
export async function signedDocument(bucket:string,path:string){const{data,error}=await supabase.storage.from(bucket).createSignedUrl(path,300);fail(error);return data?.signedUrl||''}
