import {supabase} from '../lib/supabase';
import type {DashboardSummary,PageResult,PageState,PnlReport} from './types';

const range=(p:PageState)=>[(p.page-1)*p.pageSize,p.page*p.pageSize-1] as const;
const term=(v:string)=>v.trim().replace(/[,%()]/g,' ');
function applyDate(q:any,col:string,p:PageState){if(p.from)q=q.gte(col,p.from);if(p.to)q=q.lte(col,p.to);return q}
function finish(q:any,p:PageState){const[a,b]=range(p);return q.order(p.sort,{ascending:p.ascending}).range(a,b)}
function fail(error:any){if(error)throw new Error(error.message||'Request failed')}
function saved<T>(data:T|null):T{if(!data)throw new Error('The server did not return the saved record. Please retry.');return data}

export async function dashboardSummary(start:string,end:string){const{data,error}=await supabase.rpc('get_dashboard_summary',{p_start:start,p_end:end});fail(error);return data as DashboardSummary}
export async function pnlReport(start:string,end:string,prevStart:string,prevEnd:string){const{data,error}=await supabase.rpc('get_pnl_report',{p_start:start,p_end:end,p_prev_start:prevStart,p_prev_end:prevEnd});fail(error);return data as PnlReport}
export async function deliveriesPage(p:PageState):Promise<PageResult<any>>{let q:any=supabase.from('deliveries').select('id,delivery_number,delivery_date,customer_id,driver_id,vehicle_id,source_type,from_location,to_location,description,status,expected_income,payment_status,notes,delivered_at,customers(name,email,phone,address),vehicles(registration_number),profiles!deliveries_driver_id_fkey(full_name)',{count:'exact'}).is('archived_at',null);q=applyDate(q,'delivery_date',p);if(p.search){const s=term(p.search);q=q.or(`delivery_number.ilike.%${s}%,from_location.ilike.%${s}%,to_location.ilike.%${s}%,description.ilike.%${s}%`)}q=finish(q,p);const{data,error,count}=await q;fail(error);return{rows:data||[],count:count||0}}
export async function transactionsPage(p:PageState,direction:'income'|'expense',includeIds?:string[],excludeIds?:string[]):Promise<PageResult<any>>{let q:any=supabase.from('transactions').select('id,transaction_number,transaction_date,direction,category_id,amount,paid_amount,delivery_id,vehicle_id,driver_id,customer_id,vendor_id,description,payment_status,payment_method,source,needs_review,transaction_categories(name,code),customers(name),vendors(name),vehicles(registration_number)',{count:'exact'}).is('archived_at',null).eq('direction',direction);if(includeIds?.length)q=q.in('category_id',includeIds);if(excludeIds?.length)q=q.not('category_id','in',`(${excludeIds.join(',')})`);q=applyDate(q,'transaction_date',p);if(p.search){const s=term(p.search);q=q.or(`transaction_number.ilike.%${s}%,description.ilike.%${s}%`)}q=finish(q,p);const{data,error,count}=await q;fail(error);return{rows:data||[],count:count||0}}
export async function fuelPage(p:PageState):Promise<PageResult<any>>{let q:any=supabase.from('fuel_logs').select('id,transaction_id,vehicle_id,driver_id,delivery_id,fuel_date,litres,amount,odometer,station,notes,vehicles(registration_number),profiles!fuel_logs_driver_id_fkey(full_name)',{count:'exact'}).is('archived_at',null);q=applyDate(q,'fuel_date',p);if(p.search){const s=term(p.search);q=q.or(`station.ilike.%${s}%,notes.ilike.%${s}%`)}q=finish(q,p);const{data,error,count}=await q;fail(error);return{rows:data||[],count:count||0}}
export async function maintenancePage(p:PageState):Promise<PageResult<any>>{let q:any=supabase.from('maintenance_records').select('id,transaction_id,vehicle_id,maintenance_date,maintenance_type,odometer,description,vendor_id,cost,next_service_date,next_service_odometer,status,vehicles(registration_number),vendors(name)',{count:'exact'}).is('archived_at',null);q=applyDate(q,'maintenance_date',p);if(p.search){const s=term(p.search);q=q.or(`maintenance_type.ilike.%${s}%,description.ilike.%${s}%`)}q=finish(q,p);const{data,error,count}=await q;fail(error);return{rows:data||[],count:count||0}}
export async function vehiclesPage(p:PageState):Promise<PageResult<any>>{let q:any=supabase.from('vehicles').select('id,registration_number,make,model,year,current_odometer,status,notes',{count:'exact'}).is('archived_at',null);if(p.search){const s=term(p.search);q=q.or(`registration_number.ilike.%${s}%,make.ilike.%${s}%,model.ilike.%${s}%`)}q=finish(q,p);const{data,error,count}=await q;fail(error);return{rows:data||[],count:count||0}}
export async function masters(){const[cats,customers,vendors,vehicles,profiles,company]=await Promise.all([supabase.from('transaction_categories').select('id,code,name,direction,active,system').order('direction').order('name'),supabase.from('customers').select('id,name,phone,email,address,active').eq('active',true).order('name'),supabase.from('vendors').select('id,name,phone,email,address,active').eq('active',true).order('name'),supabase.from('vehicles').select('id,registration_number,make,model,status').is('archived_at',null).order('registration_number'),supabase.from('profiles').select('id,full_name,phone,role,active').eq('active',true).order('full_name'),supabase.from('app_settings').select('value').eq('key','company').maybeSingle()]);for(const r of[cats,customers,vendors,vehicles,profiles,company])fail(r.error);return{categories:cats.data||[],customers:customers.data||[],vendors:vendors.data||[],vehicles:vehicles.data||[],profiles:profiles.data||[],company:company.data?.value||{}}}
export async function saveDelivery(payload:any,id?:string){const q=id?supabase.from('deliveries').update(payload).eq('id',id):supabase.from('deliveries').insert(payload);const{data,error}=await q.select('id,delivery_number').single();fail(error);return saved(data)}
export async function saveTransaction(payload:any,id?:string){const q=id?supabase.from('transactions').update(payload).eq('id',id):supabase.from('transactions').insert(payload);const{data,error}=await q.select('id,transaction_number').single();fail(error);return saved(data)}
export async function saveFuel(payload:any,id?:string){const q=id?supabase.from('fuel_logs').update(payload).eq('id',id):supabase.from('fuel_logs').insert(payload);const{data,error}=await q.select('id').single();fail(error);return saved(data)}
export async function saveMaintenance(payload:any,id?:string){const q=id?supabase.from('maintenance_records').update(payload).eq('id',id):supabase.from('maintenance_records').insert(payload);const{data,error}=await q.select('id').single();fail(error);return saved(data)}
export async function saveVehicle(payload:any,id?:string){const q=id?supabase.from('vehicles').update(payload).eq('id',id):supabase.from('vehicles').insert(payload);const{data,error}=await q.select('id,registration_number').single();fail(error);return saved(data)}
export async function archiveRecord(table:string,id:string,userId:string){const{error}=await supabase.from(table).update({archived_at:new Date().toISOString(),archived_by:userId}).eq('id',id);fail(error)}
export async function createMaster(kind:'customer'|'vendor'|'vehicle',payload:any){const table=kind==='customer'?'customers':kind==='vendor'?'vendors':'vehicles';const{data,error}=await supabase.from(table).insert(payload).select('*').single();fail(error);return saved(data)}
export async function mergeVehicles(target:string,sources:string[]){const{data,error}=await supabase.rpc('merge_vehicles',{p_target:target,p_sources:sources});fail(error);return data}
export async function uploadDocuments(entityType:string,entityId:string,files:File[],userId:string){for(const file of files){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${userId}/${entityType}/${entityId}/${Date.now()}-${safe}`;const up=await supabase.storage.from('truck-documents').upload(path,file,{contentType:file.type||'application/octet-stream'});fail(up.error);const ins=await supabase.from('documents').insert({entity_type:entityType,entity_id:entityId,bucket:'truck-documents',path,original_name:file.name,mime_type:file.type||null,size_bytes:file.size,uploaded_by:userId});fail(ins.error)}}
export async function documentsFor(entityType:string,entityId:string){const{data,error}=await supabase.from('documents').select('id,original_name,mime_type,size_bytes,bucket,path,created_at').eq('entity_type',entityType).eq('entity_id',entityId).order('created_at',{ascending:false});fail(error);return data||[]}
export async function signedDocument(bucket:string,path:string){const{data,error}=await supabase.storage.from(bucket).createSignedUrl(path,300);fail(error);return data?.signedUrl||''}
