import {lazy,Suspense,useEffect,useMemo,useState} from 'react';
import {useIsFetching,useQuery} from '@tanstack/react-query';
import {BarChart3,Gauge,LogOut,Menu,Receipt,RefreshCw,Settings,Truck,Wallet,X} from 'lucide-react';
import {clearDataCache,supabase} from '../lib/supabase';
import {masters} from './api';
import {Loading,ErrorState} from './components';
import {qk,queryClient} from './query';
import {useLiveInvalidation} from './live';
import type {Profile} from './types';
import './v13.css';
import './v14.css';

const DashboardPage=lazy(()=>import('./DashboardPage'));const IncomePage=lazy(()=>import('./IncomePage'));const ExpensesPage=lazy(()=>import('./ExpensesPage'));const ReportsPage=lazy(()=>import('./ReportsPage'));const FleetPage=lazy(()=>import('./FleetPage'));const SettingsPage=lazy(()=>import('./SettingsPage'));
const VERSION='1.4.1';
const nav=[['dashboard','Dashboard',BarChart3],['income','Income',Wallet],['expenses','Expenses',Receipt],['reports','Reports',Gauge],['fleet','Fleet',Truck],['settings','Settings',Settings]] as const;
export default function AppV13({profile,session}:{profile:Profile;session:any}){useLiveInvalidation();const allowed=useMemo(()=>profile.role==='driver'?nav.filter(n=>['dashboard','income','expenses'].includes(n[0])):nav,[profile.role]);const initial=()=>{const saved=localStorage.getItem('acs-truck:last-page')||'dashboard';return allowed.some(n=>n[0]===saved)?saved:'dashboard'};const[page,setPageState]=useState(initial),[drawer,setDrawer]=useState(false);const fetching=useIsFetching();const needsMasters=page==='income'||page==='expenses';const mq=useQuery({queryKey:[...qk.masters,profile.role],queryFn:()=>masters(profile.role),enabled:needsMasters,staleTime:5*60_000});useEffect(()=>{window.dispatchEvent(new Event('acs:app-ready'));(window as any).__ACS_BOOT_HIDE__?.()},[]);function setPage(p:string){setPageState(p);localStorage.setItem('acs-truck:last-page',p);setDrawer(false)}async function signOut(){queryClient.clear();await clearDataCache();await supabase.auth.signOut()}const title=nav.find(n=>n[0]===page)?.[1]||'Dashboard';let content:any;if(needsMasters&&mq.isLoading)content=<Loading label="Loading form options…"/>;else if(needsMasters&&mq.error)content=<ErrorState message={(mq.error as Error).message} retry={()=>mq.refetch()}/>;else if(page==='dashboard')content=<DashboardPage go={setPage}/>;else if(page==='income')content=<IncomePage profile={profile} masters={mq.data!}/>;else if(page==='expenses')content=<ExpensesPage profile={profile} masters={mq.data!}/>;else if(page==='reports')content=<ReportsPage/>;else if(page==='fleet')content=<FleetPage profile={profile}/>;else content=<SettingsPage profile={profile}/>;return <div className="v13-app"><aside className={`v13-side ${drawer?'open':''}`}><div className="v13-brand"><div className="logo"><Truck/></div><div><b>ACS Truck</b><small>Operations · v{VERSION}</small></div><button className="close" onClick={()=>setDrawer(false)}><X/></button></div><nav>{allowed.map(([id,label,I])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><I size={19}/>{label}</button>)}</nav><div className="v13-user"><div><b>{profile.full_name||session.user.email}</b><small>{profile.role}</small></div><button title="Sign out" onClick={signOut}><LogOut size={17}/></button></div></aside><main className="v13-main"><header className="v13-head"><button className="menu" onClick={()=>setDrawer(true)}><Menu/></button><div><small>FLEET CONTROL CENTRE</small><h1>{title}</h1></div><button className={fetching?'spin-button':''} title="Refresh current data" onClick={()=>queryClient.invalidateQueries({refetchType:'active'})}><RefreshCw/></button></header><Suspense fallback={<Loading label={`Opening ${title}…`}/>}><div className="v13-page">{content}</div></Suspense></main>{drawer&&<button className="v13-shade" aria-label="Close menu" onClick={()=>setDrawer(false)}/>}</div>}
