import {ChevronLeft,ChevronRight,Edit3,Eye,Loader2,RefreshCw,Search,Trash2,X} from 'lucide-react';
import type {ReactNode} from 'react';
import type {PageState} from './types';

export function Loading({label='Loading…'}:{label?:string}){return <div className="v13-state"><Loader2 className="spin"/><b>{label}</b><span>Please wait a moment.</span></div>}
export function ErrorState({message,retry}:{message:string;retry?:()=>void}){return <div className="v13-state error"><b>Unable to load this section</b><span>{message}</span>{retry&&<button onClick={retry}><RefreshCw size={15}/>Retry</button>}</div>}
export function Empty({message='No records found.'}:{message?:string}){return <div className="v13-empty">{message}</div>}
export function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){return <div className="v13-modal-back" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className={`v13-modal ${wide?'wide':''}`}><header><h2>{title}</h2><button type="button" onClick={onClose} aria-label="Close"><X/></button></header>{children}</section></div>}
export type Column<T>={key:string;label:string;render:(row:T)=>ReactNode;mobile?:boolean;sortKey?:string};
export function DataTable<T extends {id:string}>({rows,count,state,setState,columns,loading,error,onView,onEdit,onArchive,extraActions,selected,setSelected,toolbar}:{rows:T[];count:number;state:PageState;setState:(p:PageState)=>void;columns:Column<T>[];loading:boolean;error?:string;onView?:(r:T)=>void;onEdit?:(r:T)=>void;onArchive?:(r:T)=>void;extraActions?:(r:T)=>ReactNode;selected?:Set<string>;setSelected?:(s:Set<string>)=>void;toolbar?:ReactNode}){
 const pages=Math.max(1,Math.ceil(count/state.pageSize));const all=!!selected&&rows.length>0&&rows.every(r=>selected.has(r.id));
 const toggle=(id:string)=>{if(!selected||!setSelected)return;const n=new Set(selected);n.has(id)?n.delete(id):n.add(id);setSelected(n)};
 const toggleAll=()=>{if(!selected||!setSelected)return;const n=new Set(selected);if(all)rows.forEach(r=>n.delete(r.id));else rows.forEach(r=>n.add(r.id));setSelected(n)};
 const sort=(c:Column<T>)=>{if(!c.sortKey)return;setState({...state,page:1,sort:c.sortKey,ascending:state.sort===c.sortKey?!state.ascending:true})};
 const actions=!!(onView||onEdit||onArchive||extraActions);
 return <section className="v13-register"><div className="v13-table-tools"><label className="v13-search"><Search size={17}/><input value={state.search} placeholder="Search records" onChange={e=>setState({...state,page:1,search:e.target.value})}/></label><label>From<input type="date" value={state.from||''} onChange={e=>setState({...state,page:1,from:e.target.value||undefined})}/></label><label>To<input type="date" min={state.from} value={state.to||''} onChange={e=>setState({...state,page:1,to:e.target.value||undefined})}/></label><select value={state.pageSize} onChange={e=>setState({...state,page:1,pageSize:Number(e.target.value)})}>{[10,25,50,100].map(n=><option key={n}>{n}</option>)}</select>{toolbar}</div>{error?<ErrorState message={error}/>:loading?<Loading label="Loading records…"/>:<>{!rows.length?<Empty/>:<><div className="v13-table-wrap"><table><thead><tr>{selected&&<th><input type="checkbox" checked={all} onChange={toggleAll}/></th>}{columns.map(c=><th key={c.key} className={c.sortKey?'sortable':''} onClick={()=>sort(c)}>{c.label}{state.sort===c.sortKey?<small>{state.ascending?' ▲':' ▼'}</small>:null}</th>)}{actions&&<th>Actions</th>}</tr></thead><tbody>{rows.map(r=><tr key={r.id}>{selected&&<td><input type="checkbox" checked={selected.has(r.id)} onChange={()=>toggle(r.id)}/></td>}{columns.map(c=><td key={c.key}>{c.render(r)}</td>)}{actions&&<td><div className="v13-actions">{extraActions?.(r)}{onView&&<button title="View" onClick={()=>onView(r)}><Eye size={15}/></button>}{onEdit&&<button title="Edit" onClick={()=>onEdit(r)}><Edit3 size={15}/></button>}{onArchive&&<button className="danger" title="Archive" onClick={()=>onArchive(r)}><Trash2 size={15}/></button>}</div></td>}</tr>)}</tbody></table></div><div className="v13-mobile-list">{rows.map(r=><article key={r.id}>{selected&&<input className="select" type="checkbox" checked={selected.has(r.id)} onChange={()=>toggle(r.id)}/>}<div className="fields">{columns.filter(c=>c.mobile!==false).slice(0,5).map(c=><div key={c.key}><small>{c.label}</small><span>{c.render(r)}</span></div>)}</div>{actions&&<div className="v13-actions">{extraActions?.(r)}{onView&&<button onClick={()=>onView(r)}><Eye size={15}/>View</button>}{onEdit&&<button onClick={()=>onEdit(r)}><Edit3 size={15}/>Edit</button>}{onArchive&&<button className="danger" onClick={()=>onArchive(r)}><Trash2 size={15}/>Archive</button>}</div>}</article>)}</div></>}</>}<footer className="v13-pager"><span>{count.toLocaleString()} record(s)</span><button disabled={state.page<=1} onClick={()=>setState({...state,page:state.page-1})}><ChevronLeft/></button><b>{state.page} / {pages}</b><button disabled={state.page>=pages} onClick={()=>setState({...state,page:state.page+1})}><ChevronRight/></button></footer></section>
}
