import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {ChevronRight,Receipt,Truck} from 'lucide-react';
import {dashboardSummary} from './api';
import {bounds,dateLabel,money} from './format';
import {qk} from './query';
import {ErrorState,Loading} from './components';

export default function DashboardPage({go}:{go:(p:string)=>void}){const[period,setPeriod]=useState<'month'|'year'|'all'>('year');const b=bounds(period);const q=useQuery({queryKey:qk.dashboard(b.start,b.end),queryFn:()=>dashboardSummary(b.start,b.end)});if(q.isLoading)return <Loading label="Loading dashboard…"/>;if(q.error)return <ErrorState message={(q.error as Error).message} retry={()=>q.refetch()}/>;const d=q.data!;const net=Number(d.income)-Number(d.expenses);const cards=[['Income',money(d.income),'income'],['Expenses',money(d.expenses),'expenses'],['Net P/L',money(net),'reports'],['Receivables',money(d.receivables),'reports'],['Pending',String(d.pending),'income'],['Completed',String(d.completed),'income'],['Fleet vehicles',String(d.vehicles),'fleet'],['Maintenance',String(d.maintenance),'expenses']];return <><section className="v13-period"><div><small>MANAGEMENT PERIOD</small><strong>{b.label}</strong></div><div>{(['month','year','all'] as const).map(k=><button className={period===k?'active':''} key={k} onClick={()=>setPeriod(k)}>{k==='month'?'This Month':k==='year'?'This Year':'All Time'}</button>)}</div></section><section className="v13-metrics">{cards.map(([title,value,target])=><button key={title} onClick={()=>go(target)}><small>{title}</small><strong className={title==='Net P/L'&&net<0?'negative':''}>{value}</strong><span>{title==='Fleet vehicles'?'Current fleet':b.label}</span><ChevronRight size={15}/></button>)}</section><section className="v13-dashboard-grid"><article><header><h2>Recent deliveries</h2><small>{b.label}</small></header>{d.recent_deliveries?.map((r:any)=><button key={r.id} onClick={()=>go('income')}><Truck size={16}/><span><b>{r.delivery_number}</b><small>{r.customer_name||'No customer'} · {r.from_location||'—'} → {r.to_location||'—'}</small></span><em>{String(r.status).replace(/_/g,' ')}</em></button>)}{!d.recent_deliveries?.length&&<p>No deliveries in this period.</p>}</article><article><header><h2>Recent transactions</h2><small>{b.label}</small></header>{d.recent_transactions?.map((r:any)=><button key={r.id} onClick={()=>go(r.direction==='income'?'income':'expenses')}><Receipt size={16}/><span><b>{r.category_name||r.transaction_number}</b><small>{dateLabel(r.transaction_date)} · {r.description||''}</small></span><em className={r.direction==='income'?'positive':'negative'}>{r.direction==='income'?'+':'-'}{money(r.amount)}</em></button>)}{!d.recent_transactions?.length&&<p>No transactions in this period.</p>}</article></section></>}
