import {supabase} from '../lib/supabase';

export type DocumentKind='receipt'|'invoice'|'proof_of_delivery'|'photo'|'maintenance_document'|'other';
export type StoredDocument={id:string;entity_type:string;entity_id:string;document_kind:DocumentKind;description?:string|null;original_name:string;mime_type?:string|null;size_bytes?:number|null;bucket:string;path:string;created_at:string};

const MAX_BYTES=10*1024*1024;
const ALLOWED=new Set(['image/jpeg','image/png','image/webp','application/pdf']);
function fail(error:any){if(error)throw new Error(error.message||'Document request failed')}
function defaultKind(entityType:string):DocumentKind{if(entityType==='fuel')return'receipt';if(entityType==='maintenance')return'maintenance_document';if(entityType==='delivery')return'proof_of_delivery';if(entityType==='transaction')return'receipt';return'other'}
function safeName(name:string){return name.normalize('NFKD').replace(/[^a-zA-Z0-9._-]/g,'_').replace(/_+/g,'_').slice(-120)||'document'}

export async function uploadRecordDocuments(entityType:string,entityId:string,files:File[],kind?:DocumentKind,description?:string){const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Your session has expired. Sign in again.');const saved:StoredDocument[]=[];for(const file of files){if(file.size>MAX_BYTES)throw new Error(`${file.name} is larger than 10 MB.`);if(file.type&&!ALLOWED.has(file.type))throw new Error(`${file.name} is not a supported PDF or image file.`);const path=`${user.id}/${entityType}/${entityId}/${crypto.randomUUID()}-${safeName(file.name)}`;const up=await supabase.storage.from('truck-documents').upload(path,file,{contentType:file.type||'application/octet-stream',cacheControl:'3600',upsert:false});fail(up.error);const metadata={entity_type:entityType,entity_id:entityId,bucket:'truck-documents',path,original_name:file.name,mime_type:file.type||null,size_bytes:file.size,uploaded_by:user.id,document_kind:kind||defaultKind(entityType),description:description||null};const ins=await supabase.from('documents').insert(metadata).select('id,entity_type,entity_id,document_kind,description,original_name,mime_type,size_bytes,bucket,path,created_at').single();if(ins.error){await supabase.storage.from('truck-documents').remove([path]);fail(ins.error)}saved.push(ins.data as StoredDocument)}return saved}

export async function recordDocuments(entityType:string,entityId:string){const{data,error}=await supabase.from('documents').select('id,entity_type,entity_id,document_kind,description,original_name,mime_type,size_bytes,bucket,path,created_at').eq('entity_type',entityType).eq('entity_id',entityId).order('created_at',{ascending:false});fail(error);return(data||[]) as StoredDocument[]}
export async function openStoredDocument(doc:Pick<StoredDocument,'bucket'|'path'>){const{data,error}=await supabase.storage.from(doc.bucket).createSignedUrl(doc.path,300,{download:false});fail(error);if(!data?.signedUrl)throw new Error('Could not create a secure document link.');window.open(data.signedUrl,'_blank','noopener,noreferrer')}
export async function downloadStoredDocument(doc:Pick<StoredDocument,'bucket'|'path'|'original_name'>){const{data,error}=await supabase.storage.from(doc.bucket).download(doc.path);fail(error);if(!data)throw new Error('The server did not return the document.');const url=URL.createObjectURL(data);const a=document.createElement('a');a.href=url;a.download=doc.original_name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
