import {useMemo,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Plus,Trash2} from 'lucide-react';
import {archiveRecord,fuelExport,fuelPage,maintenanceExport,maintenancePage,transactionsExport,transactionsPage} from './api';
import {DataTable,Modal,type Column} from './components';
import ExcelExport,{type ExportColumn} from './ExcelExport';
import {FuelForm,MaintenanceForm,TransactionForm} from './forms';
import {clean,dateLabel,money} from './format';
import {qk,queryClient} from './query';
import RecordDetail from './RecordDetail';
import type {PageState,Profile} from './types';

type Masters={categories:any[];customers:any[];vendors:any[];vehicles:any[];profiles:any[];company:any};
const base=(sort:string):PageState=>({page:1,pageSize:25,search:'',sort,ascending:false});
const fuelCols:Column<any>[]=[{key:'date',label:'Date',sortKey:'fuel_date',render:r=>dateLabel(r.fuel_date)},{key:'vehicle',label:'Vehicle',render:r=>r.vehicles?.registration_number||'—'},{key:'driver',label:'Driver',render:r=>r.profiles?.full_name||'—'},{key:'litres',label:'Litres',sortKey:'litres',render:r=>r.litres??'—'},{key:'amount',label:'Amount',sortKey:'amount',render:r=>money(r.amount)},{key:'station',label:'Station',render:r=>r.station||'—'}];
const maintCols:Column<any>[]=[{key:'date',label:'Date',sortKey:'maintenance_date',render:r=>dateLabel(r.maintenance_date)},{key:'vehicle',label:'Vehicle',render:r=>r.vehicles?.registration_number||'—'},{key:'type',label:'Type',sortKey:'maintenance_type',render:r=>clean(r.maintenance_type)},{key:'desc',label:'Description',render:r=>r.description},{key:'cost',label:'Cost',sortKey:'cost',render:r=>money(r.cost)},{key:'status',label:'Status',sortKey:'status',render:r=>clean(r.status)}];
const txCols:Column<any>[]=[{key:'ref',label:'Reference',sortKey:'transaction_number',render:r=><b>{r.transaction_number}</b>},{key:'date',label:'Date',sortKey:'transaction_date',render:r=>dateLabel(r.transaction_date)},{key:'category',label:'Category',render:r=>r.transaction_categories?.name||'Unclassified'},{key:'desc',label:'Description',render:r=>r.description||'—'},{key:'amount',label:'Amount',sortKey:'amount',render:r=>money(r.amount)},{key:'status',label:'Payment',sortKey:'payment_status',render:r=>clean(r.payment_status)}];
const fuelExportCols:ExportColumn<any>[]=[{key:'date',label:'Date',value:r=>r.fuel_date},{key:'vehicle',label:'Vehicle',value:r=>r.vehicles?.registration_number||''},{key:'driver',label:'Driver',value:r=>r.profiles?.full_name||''},{key:'litres',label:'Litres',value:r=>Number(r.litres||0)},{key:'amount',label:'Amount',value:r=>Number(r.amount||0)},{key:'odometer',label:'Odometer',value:r=>r.odometer||''},{key:'station',label:'Station',value:r=>r.station||''},{key:'notes',label:'Notes',value:r=>r.notes||'',default:false}];
const maintExportCols:ExportColumn<any>[]=[{key:'date',label:'Date',value:r=>r.maintenance_date},{key:'vehicle',label:'Vehicle',value:r=>r.vehicles?.registration_number||''},{key:'type',label:'Type',value:r=>r.maintenance_type||''},{key:'description',label:'Description',value:r=>r.description||''},{key:'vendor',label:'Vendor',value:r=>r.vendors?.name||''},{key:'cost',label:'Cost',value:r=>Number(r.cost||0)},{key:'odometer',label:'Odometer',value:r=>r.odometer||''},{key:'status',label:'Status',value:r=>r.status||''},{key:'nextDate',label:'Next Service Date',value:r=>r.next_service_date||'',default:false}];
const txExportCols:ExportColumn<any>[]=[{key:'reference',label:'Reference',value:r=>r.transaction_number},{key:'date',label:'Date',value:r=>r.transaction_date},{key:'category',label:'Category',value:r=>r.transaction_categories?.name||''},{key:'vendor',label:'Vendor',value:r=>r.vendors?.name||''},{key:'vehicle',label:'Vehicle',value:r=>r.vehicles?.registration_number||''},{key:'description',label:'Description',value:r=>r.description||''},{key:'amount',label:'Amount',value:r=>Number(r.amount||0)},{key:'paid',label:'Paid Amount',value:r=>Number(r.paid_amount||0)},{key:'balance',label:'Outstanding',value:r=>Math.max(0,Number(r.amount||0)-Number(r.paid_amount||0))},{key:'payment',label:'Payment Status',value:r=>r.payment_status||''},{key:'method',label:'Payment Method',value:r=>r.payment_method||'',default:false}];
export default function ExpensesPage({profile,masters}:{profile:Profile;masters:Masters}){const[view,setView]=useState<'fuel'|'maintenance'|'transactions'>('fuel'),[fuelState,setFuelState]=useState(base('fuel_date')),[maintState,setMaintState]=useState(base('maintenance_date')),[txState,setTxState]=useState(base('transaction_date')),[modal,setModal]=useState<any>(null),[selected,setSelected]=useState<Set<string>>(new Set());const expenseCats=useMemo(()=>masters.categories.filter(c=>c.direction==='expense'&&c.active),[masters.categories]);const excluded=useMemo(()=>masters.categories.filter(c=>['FUEL','MAINTENANCE'].includes(c.code)).map(c=>c.id),[masters.categories]);const fq=useQuery({queryKey:qk.fuel(fuelState),queryFn:()=>fuelPage(fuelState),enabled:view==='fuel',placeholderData:p=>p});const mq=useQuery({queryKey:qk.maintenance(maintState),queryFn:()=>maintenancePage(maintState),enabled:view==='maintenance',placeholderData:p=>p});const tq=useQuery({queryKey:qk.transactions('expense',txState),queryFn:()=>transactionsPage(txState,'expense',undefined,excluded),enabled:view==='transactions'&&profile.role!=='driver',placeholderData:p=>p});const canGeneral=profile.role!=='driver',canMaint=['admin','operations'].includes(profile.role),canArchive=profile.role==='admin';let rows:any[]=[],count=0,state=txState,setState:any=setTxState,loading=false,error:any;let table='transactions',columns=txCols;if(view==='fuel'){rows=fq.data?.rows||[];count=fq.data?.count||0;state=fuelState;setState=setFuelState;loading=fq.isLoading;error=fq.error;table='fuel_logs';columns=fuelCols}else if(view==='maintenance'){rows=mq.data?.rows||[];count=mq.data?.count||0;state=maintState;setState=setMaintState;loading=mq.isLoading;error=mq.error;table='maintenance_records';columns=maintCols}else{rows=tq.data?.rows||[];count=tq.data?.count||0;loading=tq.isLoading;error=tq.error}async function archive(row:any){try{if(!confirm('Archive this record? It remains available for audit.'))return;await archiveRecord(table,row.id,profile.id);queryClient.invalidateQueries()}catch(e:any){alert(e.message)}}async function bulk(){try{if(!selected.size||!confirm(`Archive ${selected.size} selected record(s)?`))return;await Promise.all([...selected].map(id=>archiveRecord(table,id,profile.id)));setSelected(new Set());queryClient.invalidateQueries()}catch(e:any){alert(e.message)}}const addAllowed=view==='fuel'?true:view==='maintenance'?canMaint:canGeneral;const editAllowed=view==='fuel'?true:view==='maintenance'?canMaint:canGeneral;
 const exportButton=view==='fuel'?<ExcelExport filename="ACS-Fuel" sheetName="Fuel" columns={fuelExportCols} loadRows={()=>fuelExport(fuelState)}/>:view==='maintenance'?<ExcelExport filename="ACS-Maintenance" sheetName="Maintenance" columns={maintExportCols} loadRows={()=>maintenanceExport(maintState)}/>:<ExcelExport filename="ACS-Expenses" sheetName="Expenses" columns={txExportCols} loadRows={()=>transactionsExport(txState,'expense',undefined,excluded)}/>;
 return <><section className="v13-section-bar"><div><b>{view==='fuel'?'Fuel register':view==='maintenance'?'Maintenance register':'Expense register'}</b><small>{view==='transactions'?'Expense category is selected when recording or filtering.':'Operational expense detail.'}</small></div>{profile.role!=='driver'&&<label>Record type<select value={view} onChange={e=>{setView(e.target.value as any);setSelected(new Set())}}><option value="fuel">Fuel</option><option value="maintenance">Maintenance</option><option value="transactions">Other expenses</option></select></label>}{view==='transactions'&&<label>Category<select value={txState.categoryId||''} onChange={e=>setTxState({...txState,page:1,categoryId:e.target.value||undefined})}><option value="">All categories</option>{expenseCats.filter(c=>!['FUEL','MAINTENANCE'].includes(c.code)).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}</section><DataTable rows={rows} count={count} state={state} setState={setState} columns={columns} loading={loading} error={error?.message} selected={canArchive?selected:undefined} setSelected={canArchive?setSelected:undefined} toolbar={<>{exportButton}{addAllowed&&<button className="primary" onClick={()=>setModal({kind:view==='transactions'?'other':view})}><Plus size={15}/>Add</button>}{canArchive&&selected.size>0&&<button className="danger" onClick={bulk}><Trash2 size={15}/>Archive {selected.size}</button>}</>} onView={r=>setModal({kind:'detail',record:r,type:view==='fuel'?'fuel':view==='maintenance'?'maintenance':'transaction'})} onEdit={editAllowed?(r=>setModal({kind:view==='transactions'?'other':view,record:r})):undefined} onArchive={canArchive?archive:undefined}/>{modal&&<Modal title={modal.kind==='fuel'?(modal.record?'Edit fuel':'New fuel'):modal.kind==='maintenance'?(modal.record?'Edit maintenance':'New maintenance'):modal.kind==='other'?(modal.record?'Edit expense':'New expense'):'Record details'} onClose={()=>setModal(null)} wide={modal.kind==='detail'}>{modal.kind==='fuel'?<FuelForm record={modal.record} masters={masters} profile={profile} onDone={()=>{setModal(null);queryClient.invalidateQueries()}}/>:modal.kind==='maintenance'?<MaintenanceForm record={modal.record} masters={masters} profile={profile} onDone={()=>{setModal(null);queryClient.invalidateQueries()}}/>:modal.kind==='other'?<TransactionForm record={modal.record} direction="expense" masters={masters} profile={profile} onDone={()=>{setModal(null);queryClient.invalidateQueries()}}/>:<RecordDetail type={modal.type} record={modal.record}/>}</Modal>}</>}
