import {useMemo,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Plus,Trash2} from 'lucide-react';
import {archiveRecord,fuelPage,maintenancePage,transactionsPage} from './api';
import {DataTable,Modal,type Column} from './components';
import {FuelForm,MaintenanceForm,TransactionForm} from './forms';
import {clean,dateLabel,money} from './format';
import {qk,queryClient} from './query';
import RecordDetail from './RecordDetail';
import type {PageState,Profile} from './types';

type Masters={categories:any[];customers:any[];vendors:any[];vehicles:any[];profiles:any[];company:any};
const base=(sort:string):PageState=>({page:1,pageSize:25,search:'',sort,ascending:false});
const fuelCols:Column<any>[]=[{key:'date',label:'Date',sortKey:'fuel_date',render:r=>dateLabel(r.fuel_date)},{key:'vehicle',label:'Vehicle',render:r=>r.vehicles?.registration_number||'—'},{key:'driver',label:'Driver',render:r=>r.profiles?.full_name||'—'},{key:'litres',label:'Litres',sortKey:'litres',render:r=>r.litres??'—'},{key:'amount',label:'Amount',sortKey:'amount',render:r=>money(r.amount)},{key:'station',label:'Station',render:r=>r.station||'—'}];
const maintCols:Column<any>[]=[{key:'date',label:'Date',sortKey:'maintenance_date',render:r=>dateLabel(r.maintenance_date)},{key:'vehicle',label:'Vehicle',render:r=>r.vehicles?.registration_number||'—'},{key:'type',label:'Type',sortKey:'maintenance_type',render:r=>clean(r.maintenance_type)},{key:'desc',label:'Description',render:r=>r.description},{key:'cost',label:'Cost',sortKey:'cost',render:r=>money(r.cost)},{key:'status',label:'Status',sortKey:'status',render:r=>clean(r.status)}];
const txCols:Column<any>[]=[{key:'ref',label:'Reference',sortKey:'transaction_number',render:r=><b>{r.transaction_number}</b>},{key:'date',label:'Date',sortKey:'transaction_date',render:r=>dateLabel(r.transaction_date)},{key:'category',label:'Category',render:r=>r.transaction_categories?.name||'Unclassified'},{key:'desc',label:'Description',render:r=>r.description||'—'},{key:'amount',label:'Amount',sortKey:'amount',render:r=>money(r.amount)},{key:'status',label:'Payment',sortKey:'payment_status',render:r=>clean(r.payment_status)}];
export default function ExpensesPage({profile,masters}:{profile:Profile;masters:Masters}){const[tab,setTab]=useState<'fuel'|'maintenance'|'other'>('fuel'),[fuelState,setFuelState]=useState(base('fuel_date')),[maintState,setMaintState]=useState(base('maintenance_date')),[txState,setTxState]=useState(base('transaction_date')),[modal,setModal]=useState<any>(null),[selected,setSelected]=useState<Set<string>>(new Set());const excluded=useMemo(()=>masters.categories.filter(c=>['FUEL','MAINTENANCE'].includes(c.code)).map(c=>c.id),[masters.categories]);const fq=useQuery({queryKey:qk.fuel(fuelState),queryFn:()=>fuelPage(fuelState),enabled:tab==='fuel',placeholderData:p=>p});const mq=useQuery({queryKey:qk.maintenance(maintState),queryFn:()=>maintenancePage(maintState),enabled:tab==='maintenance',placeholderData:p=>p});const tq=useQuery({queryKey:qk.transactions('expense-other',txState),queryFn:()=>transactionsPage(txState,'expense',undefined,excluded),enabled:tab==='other',placeholderData:p=>p});const canGeneral=profile.role!=='driver',canMaint=['admin','operations'].includes(profile.role),canArchive=profile.role==='admin';let rows:any[]=[],count=0,state=txState,setState:any=setTxState,loading=false,error:any;let table='transactions',columns=txCols;if(tab==='fuel'){rows=fq.data?.rows||[];count=fq.data?.count||0;state=fuelState;setState=setFuelState;loading=fq.isLoading;error=fq.error;table='fuel_logs';columns=fuelCols}else if(tab==='maintenance'){rows=mq.data?.rows||[];count=mq.data?.count||0;state=maintState;setState=setMaintState;loading=mq.isLoading;error=mq.error;table='maintenance_records';columns=maintCols}else{rows=tq.data?.rows||[];count=tq.data?.count||0;loading=tq.isLoading;error=tq.error}async function archive(row:any){try{if(!confirm('Archive this record? It remains available for audit.'))return;await archiveRecord(table,row.id,profile.id);queryClient.invalidateQueries()}catch(e:any){alert(e.message)}}async function bulk(){try{if(!selected.size||!confirm(`Archive ${selected.size} selected record(s)?`))return;await Promise.all([...selected].map(id=>archiveRecord(table,id,profile.id)));setSelected(new Set());queryClient.invalidateQueries()}catch(e:any){alert(e.message)}}
 const addAllowed=tab==='fuel'?true:tab==='maintenance'?canMaint:canGeneral;const editAllowed=tab==='fuel'?true:tab==='maintenance'?canMaint:canGeneral;
 return <><div className="v13-tabs"><button className={tab==='fuel'?'active':''} onClick={()=>{setTab('fuel');setSelected(new Set())}}>Fuel</button><button className={tab==='maintenance'?'active':''} onClick={()=>{setTab('maintenance');setSelected(new Set())}}>Maintenance</button>{profile.role!=='driver'&&<button className={tab==='other'?'active':''} onClick={()=>{setTab('other');setSelected(new Set())}}>Other expenses</button>}</div><DataTable rows={rows} count={count} state={state} setState={setState} columns={columns} loading={loading} error={error?.message} selected={canArchive?selected:undefined} setSelected={canArchive?setSelected:undefined} toolbar={<>{addAllowed&&<button className="primary" onClick={()=>setModal({kind:tab})}><Plus size={15}/>Add</button>}{canArchive&&selected.size>0&&<button className="danger" onClick={bulk}><Trash2 size={15}/>Archive {selected.size}</button>}</>} onView={r=>setModal({kind:'detail',record:r,type:tab==='fuel'?'fuel':tab==='maintenance'?'maintenance':'transaction'})} onEdit={editAllowed?(r=>setModal({kind:tab,record:r})):undefined} onArchive={canArchive?archive:undefined}/>{modal&&<Modal title={modal.kind==='fuel'?(modal.record?'Edit fuel':'New fuel'):modal.kind==='maintenance'?(modal.record?'Edit maintenance':'New maintenance'):modal.kind==='other'?(modal.record?'Edit expense':'New expense'):'Record details'} onClose={()=>setModal(null)} wide={modal.kind==='detail'}>{modal.kind==='fuel'?<FuelForm record={modal.record} masters={masters} profile={profile} onDone={()=>{setModal(null);queryClient.invalidateQueries()}}/>:modal.kind==='maintenance'?<MaintenanceForm record={modal.record} masters={masters} profile={profile} onDone={()=>{setModal(null);queryClient.invalidateQueries()}}/>:modal.kind==='other'?<TransactionForm record={modal.record} direction="expense" masters={masters} profile={profile} onDone={()=>{setModal(null);queryClient.invalidateQueries()}}/>:<RecordDetail type={modal.type} record={modal.record}/>}</Modal>}</>}
