import {useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {GitMerge,Plus,Save} from 'lucide-react';
import {archiveRecord,mergeVehicles,saveVehicle,vehiclesExport,vehiclesPage} from './api';
import {DataTable,Modal,type Column} from './components';
import ExcelExport,{type ExportColumn} from './ExcelExport';
import {VehicleForm} from './forms';
import {clean} from './format';
import {qk,queryClient} from './query';
import RecordDetail from './RecordDetail';
import type {PageState,Profile} from './types';

const cols:Column<any>[]=[{key:'registration',label:'Registration',sortKey:'registration_number',render:r=><b>{r.registration_number}</b>},{key:'make',label:'Make / Model',sortKey:'make',render:r=>[r.make,r.model].filter(Boolean).join(' ')||'—'},{key:'year',label:'Year',sortKey:'year',render:r=>r.year||'—'},{key:'odometer',label:'Odometer',sortKey:'current_odometer',render:r=>Number(r.current_odometer||0).toLocaleString()},{key:'status',label:'Status',sortKey:'status',render:r=><span className={`v13-status ${r.status}`}>{clean(r.status)}</span>}];
const exportCols:ExportColumn<any>[]=[{key:'registration',label:'Registration',value:r=>r.registration_number},{key:'make',label:'Make',value:r=>r.make||''},{key:'model',label:'Model',value:r=>r.model||''},{key:'year',label:'Year',value:r=>r.year||''},{key:'odometer',label:'Odometer',value:r=>Number(r.current_odometer||0)},{key:'status',label:'Status',value:r=>r.status||''},{key:'notes',label:'Notes',value:r=>r.notes||'',default:false}];
const initial:PageState={page:1,pageSize:25,search:'',sort:'registration_number',ascending:true};
export default function FleetPage({profile}:{profile:Profile}){const[state,setState]=useState(initial),[selected,setSelected]=useState<Set<string>>(new Set()),[modal,setModal]=useState<any>(null),[bulkStatus,setBulkStatus]=useState(''),[target,setTarget]=useState(''),[busy,setBusy]=useState(false);const q=useQuery({queryKey:qk.vehicles(state),queryFn:()=>vehiclesPage(state),placeholderData:p=>p});const canEdit=['admin','operations'].includes(profile.role),isAdmin=profile.role==='admin';async function archive(r:any){if(!confirm(`Archive ${r.registration_number}?`))return;await archiveRecord('vehicles',r.id,profile.id);queryClient.invalidateQueries()}async function applyStatus(){if(!selected.size||!bulkStatus)return;setBusy(true);try{await Promise.all([...selected].map(id=>saveVehicle({status:bulkStatus},id)));setSelected(new Set());setBulkStatus('');queryClient.invalidateQueries({queryKey:['vehicles']});queryClient.invalidateQueries({queryKey:['masters']})}finally{setBusy(false)}}async function merge(){if(selected.size<2||!target)return;if(!selected.has(target))return alert('The merge target must be one of the selected vehicles.');const sources=[...selected].filter(id=>id!==target);const t=q.data?.rows.find((v:any)=>v.id===target);if(!confirm(`Merge ${sources.length} selected vehicle record(s) into ${t?.registration_number}? This will move linked operations atomically and archive the duplicate records.`))return;setBusy(true);try{await mergeVehicles(target,sources);setSelected(new Set());setTarget('');queryClient.invalidateQueries()}catch(e:any){alert(e.message)}finally{setBusy(false)}}const toolbar=<><ExcelExport filename="ACS-Fleet" sheetName="Fleet" columns={exportCols} loadRows={()=>vehiclesExport(state)}/>{canEdit&&<button className="primary" onClick={()=>setModal({kind:'vehicle'})}><Plus size={15}/>Add</button>}{isAdmin&&selected.size>0&&<><select value={bulkStatus} onChange={e=>setBulkStatus(e.target.value)}><option value="">Bulk status…</option><option value="active">Active</option><option value="maintenance">Maintenance</option><option value="inactive">Inactive</option></select><button disabled={!bulkStatus||busy} onClick={applyStatus}><Save size={15}/>Update {selected.size}</button></>}{isAdmin&&selected.size>=2&&<><select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Merge into…</option>{q.data?.rows.filter((v:any)=>selected.has(v.id)).map((v:any)=><option key={v.id} value={v.id}>{v.registration_number}</option>)}</select><button className="danger" disabled={!target||busy} onClick={merge}><GitMerge size={15}/>Merge</button></>}</>;
 return <><DataTable rows={q.data?.rows||[]} count={q.data?.count||0} state={state} setState={setState} columns={cols} loading={q.isLoading} error={q.error?.message} selected={isAdmin?selected:undefined} setSelected={isAdmin?setSelected:undefined} toolbar={toolbar} onView={r=>setModal({kind:'detail',record:r})} onEdit={canEdit?(r=>setModal({kind:'vehicle',record:r})):undefined} onArchive={isAdmin?archive:undefined}/>{modal&&<Modal title={modal.kind==='vehicle'?(modal.record?'Edit vehicle':'New vehicle'):'Vehicle details'} onClose={()=>setModal(null)}>{modal.kind==='vehicle'?<VehicleForm record={modal.record} onDone={()=>{setModal(null);queryClient.invalidateQueries()}}/>:<RecordDetail type="vehicle" record={modal.record}/>}</Modal>}</>}
