import {useMemo,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {FileText,Plus,StepForward,Trash2} from 'lucide-react';
import {archiveRecord,deliveriesPage,saveDelivery,transactionsPage} from './api';
import {DataTable,Modal,type Column} from './components';
import {DeliveryForm,TransactionForm} from './forms';
import {clean,dateLabel,money} from './format';
import {invoicePdf} from './pdf';
import {qk,queryClient} from './query';
import RecordDetail from './RecordDetail';
import type {PageState,Profile} from './types';

type Masters={categories:any[];customers:any[];vendors:any[];vehicles:any[];profiles:any[];company:any};
const base=(sort:string):PageState=>({page:1,pageSize:25,search:'',sort,ascending:false});
const deliveryCols:Column<any>[]=[{key:'ref',label:'Delivery',sortKey:'delivery_number',render:r=><b>{r.delivery_number}</b>},{key:'date',label:'Date',sortKey:'delivery_date',render:r=>dateLabel(r.delivery_date)},{key:'customer',label:'Customer',render:r=>r.customers?.name||'—'},{key:'route',label:'Route',render:r=>`${r.from_location||'—'} → ${r.to_location||'—'}`},{key:'amount',label:'Income',sortKey:'expected_income',render:r=>money(r.expected_income)},{key:'status',label:'Status',sortKey:'status',render:r=><span className={`v13-status ${r.status}`}>{clean(r.status)}</span>}];
const txCols:Column<any>[]=[{key:'ref',label:'Reference',sortKey:'transaction_number',render:r=><b>{r.transaction_number}</b>},{key:'date',label:'Date',sortKey:'transaction_date',render:r=>dateLabel(r.transaction_date)},{key:'category',label:'Category',render:r=>r.transaction_categories?.name||'Unclassified'},{key:'desc',label:'Description',render:r=>r.description||'—'},{key:'amount',label:'Amount',sortKey:'amount',render:r=>money(r.amount)},{key:'status',label:'Payment',sortKey:'payment_status',render:r=>clean(r.payment_status)}];

export default function IncomePage({profile,masters}:{profile:Profile;masters:Masters}){const[tab,setTab]=useState<'deliveries'|'transport'|'other'>('deliveries'),[state,setState]=useState(base('delivery_date')),[txState,setTxState]=useState(base('transaction_date')),[modal,setModal]=useState<any>(null),[selected,setSelected]=useState<Set<string>>(new Set());const transportIds=useMemo(()=>masters.categories.filter(c=>['EXTERNAL_DELIVERY','TRUCK_HIRE','TRANSPORT_SERVICE'].includes(c.code)).map(c=>c.id),[masters.categories]);const excluded=useMemo(()=>masters.categories.filter(c=>['DELIVERY_INCOME','EXTERNAL_DELIVERY','TRUCK_HIRE','TRANSPORT_SERVICE'].includes(c.code)).map(c=>c.id),[masters.categories]);const dq=useQuery({queryKey:qk.deliveries(state),queryFn:()=>deliveriesPage(state),enabled:tab==='deliveries',placeholderData:p=>p});const tq=useQuery({queryKey:qk.transactions(`income-${tab}`,txState),queryFn:()=>transactionsPage(txState,'income',tab==='transport'?transportIds:undefined,tab==='other'?excluded:undefined),enabled:tab!=='deliveries',placeholderData:p=>p});const canEdit=['admin','operations'].includes(profile.role),canArchive=profile.role==='admin';async function archive(table:string,row:any){if(!confirm('Archive this record? It will remain in the audit history.'))return;await archiveRecord(table,row.id,profile.id);queryClient.invalidateQueries({queryKey:[table==='deliveries'?'deliveries':'transactions']});queryClient.invalidateQueries({queryKey:['dashboard']})}async function bulk(table:string){if(!selected.size||!confirm(`Archive ${selected.size} selected record(s)?`))return;await Promise.all([...selected].map(id=>archiveRecord(table,id,profile.id)));setSelected(new Set());queryClient.invalidateQueries()}async function progress(row:any){const order=['assigned','loaded','departed','arrived','delivered'];const i=order.indexOf(row.status);if(i<0||i===order.length-1)return;const next=order[i+1];if(!confirm(`Mark ${row.delivery_number} as ${next}?`))return;await saveDelivery({status:next,...(next==='delivered'?{delivered_at:new Date().toISOString()}: {})},row.id);queryClient.invalidateQueries({queryKey:['deliveries']});queryClient.invalidateQueries({queryKey:['dashboard']})}
 const rows=tab==='deliveries'?dq.data?.rows||[]:tq.data?.rows||[],count=tab==='deliveries'?dq.data?.count||0:tq.data?.count||0,current=tab==='deliveries'?state:txState,setCurrent=tab==='deliveries'?setState:setTxState;
 return <><div className="v13-tabs"><button className={tab==='deliveries'?'active':''} onClick={()=>{setTab('deliveries');setSelected(new Set())}}>Deliveries</button>{profile.role!=='driver'&&<><button className={tab==='transport'?'active':''} onClick={()=>{setTab('transport');setSelected(new Set())}}>Transport service</button><button className={tab==='other'?'active':''} onClick={()=>{setTab('other');setSelected(new Set())}}>Other income</button></>}</div><DataTable rows={rows} count={count} state={current} setState={setCurrent as any} columns={tab==='deliveries'?deliveryCols:txCols} loading={tab==='deliveries'?dq.isLoading:tq.isLoading} error={(tab==='deliveries'?dq.error:tq.error)?.message} selected={canArchive?selected:undefined} setSelected={canArchive?setSelected:undefined} toolbar={<><button className="primary" onClick={()=>setModal({kind:tab==='deliveries'?'delivery':'transaction'})}><Plus size={15}/>Add</button>{canArchive&&selected.size>0&&<button className="danger" onClick={()=>bulk(tab==='deliveries'?'deliveries':'transactions')}><Trash2 size={15}/>Archive {selected.size}</button>}</>} onView={r=>setModal({kind:'detail',record:r,type:tab==='deliveries'?'delivery':'transaction'})} onEdit={canEdit||tab!=='deliveries'?(r=>setModal({kind:tab==='deliveries'?'delivery':'transaction',record:r})):undefined} onArchive={canArchive?(r=>archive(tab==='deliveries'?'deliveries':'transactions',r)):undefined} extraActions={tab==='deliveries'?(r:any)=><>{profile.role==='driver'&&r.driver_id===profile.id&&r.status!=='delivered'&&<button title="Next status" onClick={()=>progress(r)}><StepForward size={15}/></button>}{profile.role!=='driver'&&<button title="Invoice" onClick={()=>invoicePdf(r,masters.company)}><FileText size={15}/></button>}</>:undefined}/>{modal&&<Modal title={modal.kind==='delivery'?(modal.record?'Edit delivery':'New delivery'):modal.kind==='transaction'?(modal.record?'Edit income':'New income'): 'Record details'} onClose={()=>setModal(null)} wide={modal.kind==='detail'}>{modal.kind==='delivery'?<DeliveryForm record={modal.record} masters={masters} profile={profile} onDone={()=>{setModal(null);queryClient.invalidateQueries()}}/>:modal.kind==='transaction'?<TransactionForm record={modal.record} direction="income" masters={masters} profile={profile} onDone={()=>{setModal(null);queryClient.invalidateQueries()}}/>:<RecordDetail type={modal.type} record={modal.record}/>}</Modal>}</>}
