import {useEffect,useMemo,useState} from 'react';
import {Bell,CheckCheck,X} from 'lucide-react';
import {supabase} from '../lib/supabase';

type Notice={id:string;title:string;body:string|null;notification_type:string;priority:string;action_page:string|null;read_at:string|null;created_at:string};
const ago=(s:string)=>{const d=Math.max(0,Date.now()-new Date(s).getTime()),m=Math.floor(d/60000);if(m<1)return'now';if(m<60)return`${m}m`;const h=Math.floor(m/60);if(h<24)return`${h}h`;return`${Math.floor(h/24)}d`};
export default function NotificationCenter({userId,go}:{userId:string;go:(p:string)=>void}){const[list,setList]=useState<Notice[]>([]),[open,setOpen]=useState(false),[permission,setPermission]=useState<NotificationPermission|undefined>(typeof Notification==='undefined'?undefined:Notification.permission);const unread=useMemo(()=>list.filter(n=>!n.read_at).length,[list]);
async function load(){const{data}=await supabase.from('notifications').select('id,title,body,notification_type,priority,action_page,read_at,created_at').order('created_at',{ascending:false}).limit(40);setList((data||[]) as Notice[])}
useEffect(()=>{load();const ch=supabase.channel(`notifications:${userId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications',filter:`user_id=eq.${userId}`},p=>{const n=p.new as Notice;setList(v=>[n,...v].slice(0,40));if(typeof Notification!=='undefined'&&Notification.permission==='granted'&&document.visibilityState!=='visible')new Notification(n.title,{body:n.body||undefined,icon:'/icons/acs-truck.svg',tag:n.id})}).subscribe();return()=>{supabase.removeChannel(ch)}},[userId]);
async function mark(id:string){const now=new Date().toISOString();setList(v=>v.map(n=>n.id===id?{...n,read_at:now}:n));await supabase.from('notifications').update({read_at:now}).eq('id',id)}
async function markAll(){const now=new Date().toISOString();setList(v=>v.map(n=>({...n,read_at:n.read_at||now})));await supabase.from('notifications').update({read_at:now}).is('read_at',null)}
async function enableBrowser(){if(typeof Notification==='undefined')return;const p=await Notification.requestPermission();setPermission(p)}
function openNotice(n:Notice){if(!n.read_at)mark(n.id);if(n.action_page){go(n.action_page);setOpen(false)}}
return <div className="v16-notifications"><button className="v16-bell" aria-label={`Notifications${unread?` (${unread} unread)`:''}`} title="Notifications" onClick={()=>setOpen(v=>!v)}><Bell size={19}/>{unread>0&&<b>{unread>99?'99+':unread}</b>}</button>{open&&<><button className="v16-notice-shade" aria-label="Close notifications" onClick={()=>setOpen(false)}/><section className="v16-notice-panel"><header><div><strong>Notifications</strong><small>{unread?`${unread} unread`:'You are up to date'}</small></div><div>{unread>0&&<button title="Mark all read" onClick={markAll}><CheckCheck size={17}/></button>}<button title="Close" onClick={()=>setOpen(false)}><X size={18}/></button></div></header>{permission==='default'&&<button className="v16-enable" onClick={enableBrowser}>Enable browser alerts</button>}<div className="v16-notice-list">{!list.length&&<p className="v16-empty-notice">No notifications yet.</p>}{list.map(n=><button key={n.id} className={`${n.read_at?'':'unread'} priority-${n.priority}`} onClick={()=>openNotice(n)}><span><strong>{n.title}</strong><small>{n.body}</small></span><time>{ago(n.created_at)}</time></button>)}</div></section></>}</div>}
