import {useRef,useState} from 'react';
import {useQuery} from '@tanstack/react-query';
import {Download,Eye,Paperclip,Upload} from 'lucide-react';
import {clean,dateLabel,money} from './format';
import {Loading} from './components';
import {downloadStoredDocument,openStoredDocument,recordDocuments,uploadRecordDocuments,type DocumentKind} from './documents';
import {queryClient} from './query';

const hidden=new Set(['id','transaction_id','vehicle_id','driver_id','delivery_id','customer_id','vendor_id','category_id','created_by','approved_by','archived_by','created_at','updated_at','approved_at','archived_at','legacy_month','legacy_client_name','legacy_from_location','legacy_to_location','legacy_transporter','legacy_truck_id','legacy_trans_type','source','external_reference','needs_review']);
const moneyKeys=/amount|income|cost|paid/i;const dateKeys=/date$|_at$/i;
const label=(k:string)=>k.replace(/^expected_/,'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const kindLabel=(k:string)=>({receipt:'Receipt',invoice:'Invoice',proof_of_delivery:'Proof of delivery',photo:'Photo',maintenance_document:'Maintenance document',other:'Other document'} as any)[k]||clean(k);
const defaultKind=(type:string):DocumentKind=>type==='fuel'?'receipt':type==='maintenance'?'maintenance_document':type==='delivery'?'proof_of_delivery':type==='transaction'?'receipt':'other';
export default function RecordDetail({type,record}:{type:string;record:any}){const docs=useQuery({queryKey:['documents',type,record.id],queryFn:()=>recordDocuments(type,record.id),enabled:!!record.id});const entries=Object.entries(record).filter(([k,v])=>!hidden.has(k)&&v!=null&&typeof v!=='object');const[kind,setKind]=useState<DocumentKind>(defaultKind(type)),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const picker=useRef<HTMLInputElement>(null);async function upload(files:FileList|null){if(!files?.length)return;setBusy(true);setMessage('');try{await uploadRecordDocuments(type,record.id,Array.from(files),kind);await queryClient.invalidateQueries({queryKey:['documents',type,record.id]});setMessage('File saved securely to the server.')}catch(e:any){setMessage(e.message)}finally{setBusy(false);if(picker.current)picker.current.value=''}}return <div className="v13-detail"><div className="v13-detail-grid">{entries.map(([k,v])=><div key={k}><small>{label(k)}</small><b>{moneyKeys.test(k)?money(v):dateKeys.test(k)?dateLabel(v):clean(v)}</b></div>)}</div><section className="v13-docs"><div className="v13-docs-head"><div><h3>Documents</h3><small>Stored securely in ACS Truck and available on every signed-in device.</small></div><div className="v13-doc-upload"><select aria-label="Document type" value={kind} onChange={e=>setKind(e.target.value as DocumentKind)}><option value="receipt">Receipt</option><option value="invoice">Invoice</option><option value="proof_of_delivery">Proof of delivery</option><option value="photo">Photo</option><option value="maintenance_document">Maintenance document</option><option value="other">Other</option></select><button type="button" disabled={busy} onClick={()=>picker.current?.click()}><Upload size={15}/>{busy?'Uploading…':'Upload'}</button><input ref={picker} hidden type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>upload(e.target.files)}/></div></div>{message&&<p className="v13-doc-message">{message}</p>}{docs.isLoading?<Loading label="Loading documents…"/>:docs.data?.length?<div className="v13-doc-list">{docs.data.map((d:any)=><article key={d.id}><Paperclip size={16}/><span><b>{d.original_name}</b><small>{kindLabel(d.document_kind)} · {d.size_bytes?`${Math.max(1,Math.round(d.size_bytes/1024))} KB`:d.mime_type||'Document'}</small></span><button title="Open" onClick={()=>openStoredDocument(d)}><Eye size={15}/></button><button title="Download" onClick={()=>downloadStoredDocument(d)}><Download size={15}/></button></article>)}</div>:<p>No files attached.</p>}</section></div>}
