import {FormEvent,useEffect,useMemo,useState} from 'react';
import {Building2,Camera,Check,Search,ShieldCheck,Upload,UserCog,Users,X} from 'lucide-react';
import {supabase} from './lib/supabase';

type Role='admin'|'operations'|'accounts'|'driver';
type Profile={id:string;full_name:string|null;phone:string|null;role:Role;active:boolean};
type Company={name?:string;trading_name?:string;address?:string;phone?:string;email?:string;tax_id?:string;website?:string;currency?:string;invoice_prefix?:string;invoice_terms?:string;logo_path?:string};

export default function AdminRefinements({profile}:{profile:Profile}){
  const[open,setOpen]=useState(false),[tab,setTab]=useState<'branding'|'users'>('branding');
  if(profile.role!=='admin')return null;
  return <><button className="admin-fab" onClick={()=>setOpen(true)} title="Administration"><ShieldCheck size={20}/><span>Admin</span></button>{open&&<div className="admin-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><aside className="admin-drawer"><header><div><small>ADMINISTRATION</small><h3>System controls</h3></div><button onClick={()=>setOpen(false)}><X size={20}/></button></header><nav className="admin-tabs"><button className={tab==='branding'?'active':''} onClick={()=>setTab('branding')}><Building2 size={16}/>Branding</button><button className={tab==='users'?'active':''} onClick={()=>setTab('users')}><Users size={16}/>Users</button></nav>{tab==='branding'?<Branding profile={profile}/>:<UserAdmin current={profile}/>}</aside></div>}</>
}

function Branding({profile}:{profile:Profile}){
  const[company,setCompany]=useState<Company>({}),[logoUrl,setLogoUrl]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
  useEffect(()=>{load()},[]);
  async function load(){const{data}=await supabase.from('app_settings').select('value').eq('key','company').maybeSingle();const c=(data?.value||{}) as Company;setCompany(c);if(c.logo_path){const{data:s}=await supabase.storage.from('company-assets').createSignedUrl(c.logo_path,3600);setLogoUrl(s?.signedUrl||'')}}
  async function uploadLogo(file:File){setMsg('');if(!['image/png','image/jpeg','image/webp','image/svg+xml'].includes(file.type))return setMsg('Use PNG, JPG, WEBP or SVG.');if(file.size>2*1024*1024)return setMsg('Logo must be 2 MB or smaller.');setBusy(true);const ext=(file.name.split('.').pop()||'png').toLowerCase();const path=`branding/company-logo.${ext}`;const{error}=await supabase.storage.from('company-assets').upload(path,file,{upsert:true,contentType:file.type,cacheControl:'3600'});if(error){setBusy(false);return setMsg(error.message)}const next={...company,logo_path:path};const saved=await supabase.from('app_settings').upsert({key:'company',value:next,updated_by:profile.id});if(saved.error){setBusy(false);return setMsg(saved.error.message)}setCompany(next);const{data:s}=await supabase.storage.from('company-assets').createSignedUrl(path,3600);setLogoUrl(s?.signedUrl||'');setBusy(false);setMsg('Company logo updated.')}
  async function save(e:FormEvent){e.preventDefault();setBusy(true);const{error}=await supabase.from('app_settings').upsert({key:'company',value:company,updated_by:profile.id});setBusy(false);setMsg(error?.message||'Company branding saved.')}
  return <section className="admin-section"><div className="admin-logo-card"><div className="admin-logo-preview">{logoUrl?<img src={logoUrl} alt="Company logo"/>:<Camera size={34}/>}</div><div><h4>Company logo</h4><p>Used for company identity and document branding. PNG/JPG/WEBP/SVG, max 2 MB.</p><label className="admin-upload"><Upload size={16}/>{busy?'Uploading…':'Upload logo'}<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)uploadLogo(f)}}/></label></div></div><form className="admin-form" onSubmit={save}><label>Company name<input value={company.name||''} onChange={e=>setCompany({...company,name:e.target.value})}/></label><label>Trading name<input value={company.trading_name||''} onChange={e=>setCompany({...company,trading_name:e.target.value})}/></label><label>Phone<input value={company.phone||''} onChange={e=>setCompany({...company,phone:e.target.value})}/></label><label>Email<input type="email" value={company.email||''} onChange={e=>setCompany({...company,email:e.target.value})}/></label><label className="full">Address<input value={company.address||''} onChange={e=>setCompany({...company,address:e.target.value})}/></label><label>Tax / registration ID<input value={company.tax_id||''} onChange={e=>setCompany({...company,tax_id:e.target.value})}/></label><label>Invoice prefix<input value={company.invoice_prefix||''} onChange={e=>setCompany({...company,invoice_prefix:e.target.value})}/></label><label className="full">Invoice terms<textarea rows={3} value={company.invoice_terms||''} onChange={e=>setCompany({...company,invoice_terms:e.target.value})}/></label><button className="admin-primary full" disabled={busy}><Check size={16}/>Save branding</button></form>{msg&&<div className="admin-message">{msg}</div>}</section>
}

function UserAdmin({current}:{current:Profile}){
  const[users,setUsers]=useState<Profile[]>([]),[query,setQuery]=useState(''),[editing,setEditing]=useState<Profile|null>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
  useEffect(()=>{load()},[]);
  async function load(){const{data,error}=await supabase.from('profiles').select('id,full_name,phone,role,active').order('full_name');if(error)setMsg(error.message);else setUsers((data||[]) as Profile[])}
  const filtered=useMemo(()=>users.filter(u=>`${u.full_name||''} ${u.phone||''} ${u.role}`.toLowerCase().includes(query.toLowerCase())),[users,query]);
  async function saveUser(e:FormEvent){e.preventDefault();if(!editing)return;const original=users.find(u=>u.id===editing.id);if(original&&(original.role!==editing.role||original.active!==editing.active)){const action=!editing.active?'deactivate this account':`change this user's role to ${editing.role}`;if(!confirm(`Confirm you want to ${action}. Access permissions will change immediately.`))return}setBusy(true);const{error}=await supabase.rpc('admin_update_user_profile',{p_user_id:editing.id,p_full_name:editing.full_name||'',p_phone:editing.phone||'',p_role:editing.role,p_active:editing.active});setBusy(false);if(error)return setMsg(error.message);setMsg('User access updated.');setEditing(null);load()}
  return <section className="admin-section"><div className="admin-search"><Search size={17}/><input placeholder="Search users" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="admin-user-list">{filtered.map(u=><article key={u.id}><div className="admin-avatar">{(u.full_name||'U')[0].toUpperCase()}</div><div className="admin-user-main"><b>{u.full_name||'Unnamed user'}{u.id===current.id&&<small> · You</small>}</b><span>{u.phone||'No phone'} · {u.role}</span></div><span className={`admin-state ${u.active?'on':'off'}`}>{u.active?'Active':'Inactive'}</span><button className="admin-manage" onClick={()=>setEditing({...u})}><UserCog size={16}/>Manage</button></article>)}</div>{msg&&<div className="admin-message">{msg}</div>}{editing&&<div className="admin-modal-back" onMouseDown={e=>e.target===e.currentTarget&&setEditing(null)}><form className="admin-modal" onSubmit={saveUser}><header><div><small>USER ACCESS</small><h4>Manage account</h4></div><button type="button" onClick={()=>setEditing(null)}><X size={18}/></button></header><label>Full name<input value={editing.full_name||''} onChange={e=>setEditing({...editing,full_name:e.target.value})}/></label><label>Phone<input value={editing.phone||''} onChange={e=>setEditing({...editing,phone:e.target.value})}/></label><label>Role<select value={editing.role} onChange={e=>setEditing({...editing,role:e.target.value as Role})}><option value="admin">Admin</option><option value="operations">Operations</option><option value="accounts">Accounts</option><option value="driver">Driver</option></select></label><label className="admin-toggle"><input type="checkbox" checked={editing.active} disabled={editing.id===current.id} onChange={e=>setEditing({...editing,active:e.target.checked})}/><span>Account active</span>{editing.id===current.id&&<small>Your own admin account cannot be deactivated here.</small>}</label><button className="admin-primary" disabled={busy}><Check size={16}/>{busy?'Saving…':'Save access'}</button></form></div>}</section>
}
