import {FormEvent,useEffect,useState} from 'react';
import {LogOut,ShieldAlert,Truck} from 'lucide-react';
import ProductionApp from './ProductionApp';
import AdminRefinements from './AdminRefinements';
import PWAControls from './PWAControls';
import {supabase} from './lib/supabase';

type Profile={id:string;full_name:string|null;phone:string|null;role:'admin'|'operations'|'accounts'|'driver';active:boolean};

export default function AppRoot(){const[session,setSession]=useState<any>(undefined),[profile,setProfile]=useState<Profile|null>(null),[checking,setChecking]=useState(true),[accessError,setAccessError]=useState('');useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);useEffect(()=>{if(session===undefined)return;if(!session){setProfile(null);setAccessError('');setChecking(false);return}setChecking(true);supabase.from('profiles').select('id,full_name,phone,role,active').eq('id',session.user.id).single().then(({data,error})=>{setProfile(data as Profile|null);setAccessError(error?.message||(!data?'Your user profile could not be loaded. Contact an administrator.':''));setChecking(false)})},[session]);if(checking&&session)return <div className="access-check">Checking account access…</div>;if(!session)return <><Login/><PWAControls/></>;if(accessError)return <AccessError message={accessError}/>;if(profile&&!profile.active)return <DisabledAccount/>;return profile?<><ProductionApp profile={profile} session={session}/><AdminRefinements profile={profile}/><PWAControls/></>:null}
function Login(){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');async function submit(e:FormEvent){e.preventDefault();setBusy(true);const{error}=await supabase.auth.signInWithPassword({email,password});setMsg(error?.message||'');setBusy(false)}return <main className="prod-login"><section><div className="prod-login-logo"><Truck size={28}/></div><small>AVENUE CONSTRUCTION SUPPLY GH LTD</small><h1>ACS Truck Operations</h1><p>Fleet operations, accounting and reporting.</p><form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form>{msg&&<div className="login-error">{msg}</div>}</section></main>}
function DisabledAccount(){return <main className="access-disabled"><section><ShieldAlert size={42}/><h1>Account inactive</h1><p>Your ACS Truck account has been deactivated by an administrator. Operational and financial data access is blocked until the account is reactivated.</p><button onClick={()=>supabase.auth.signOut()}><LogOut size={17}/>Sign out</button></section></main>}
function AccessError({message}:{message:string}){return <main className="access-disabled"><section><ShieldAlert size={42}/><h1>Account access unavailable</h1><p>{message}</p><button onClick={()=>supabase.auth.signOut()}><LogOut size={17}/>Sign out</button></section></main>}
