import {useEffect,useState} from 'react';
import {FileText} from 'lucide-react';
import {createPortal} from 'react-dom';
import {jsPDF} from 'jspdf';
import autoTable from 'jspdf-autotable';
import {supabase} from './lib/supabase';

const fmt=(v:any)=>v?new Date(`${String(v).slice(0,10)}T00:00:00`).toLocaleDateString('en-GH',{day:'2-digit',month:'short',year:'numeric'}):'—';
const ghs=(n:any)=>`GHS ${Number(n||0).toLocaleString('en-GH',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
async function logoPng(path?:string){if(!path)return null;try{const {data}=await supabase.storage.from('company-assets').createSignedUrl(path,300);if(!data?.signedUrl)return null;const blob=await fetch(data.signedUrl).then(r=>r.blob());if(!blob.type.includes('svg'))return await new Promise<string>((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(String(fr.result));fr.onerror=rej;fr.readAsDataURL(blob)});const url=URL.createObjectURL(blob);const img=new Image();await new Promise<void>((res,rej)=>{img.onload=()=>res();img.onerror=rej;img.src=url});const canvas=document.createElement('canvas');canvas.width=Math.max(img.naturalWidth,400);canvas.height=Math.max(img.naturalHeight,200);const ctx=canvas.getContext('2d');if(!ctx)return null;ctx.drawImage(img,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);return canvas.toDataURL('image/png')}catch{return null}}

export default function InvoiceV12Override(){const[modal,setModal]=useState<HTMLElement|null>(null);useEffect(()=>{const detect=()=>{const m=document.querySelector('.prod-modal') as HTMLElement|null;const on=m?.querySelector('header h2')?.textContent?.trim()==='Generate invoice PDF';setModal(on?m:null);m?.classList.toggle('v12-invoice-managed',!!on)};detect();const o=new MutationObserver(detect);o.observe(document.body,{subtree:true,childList:true,characterData:true});return()=>o.disconnect()},[]);if(!modal)return null;
 async function generate(){const summary=modal!.querySelector('.invoice-summary'),deliveryNumber=summary?.querySelector('span')?.textContent?.trim();if(!deliveryNumber)return alert('Delivery reference could not be determined.');const [{data:delivery,error},{data:settings}]=await Promise.all([supabase.from('deliveries').select('*,customers(name,email,phone,address),vehicles(registration_number),profiles!deliveries_driver_id_fkey(full_name)').eq('delivery_number',deliveryNumber).maybeSingle(),supabase.from('app_settings').select('value').eq('key','company').maybeSingle()]);if(error||!delivery)return alert(error?.message||'Delivery not found.');const company=settings?.value||{},inputs=[...modal!.querySelectorAll('input')] as HTMLInputElement[],invoiceNumber=inputs[0]?.value||`INV-${deliveryNumber}`,due=inputs.find(i=>i.type==='date')?.value||new Date().toISOString().slice(0,10),terms=(modal!.querySelector('textarea') as HTMLTextAreaElement|null)?.value||company.invoice_terms||'Payment due according to agreed terms.',amount=Number(delivery.expected_income||0),logo=await logoPng(company.logo_path),doc=new jsPDF('p','mm','a4'),W=doc.internal.pageSize.getWidth(),H=doc.internal.pageSize.getHeight();
 doc.setFillColor(15,23,42);doc.rect(0,0,W,10,'F');let x=18;if(logo){try{doc.addImage(logo,'PNG',18,15,25,18);x=49}catch{}}doc.setTextColor(15,23,42);doc.setFont('helvetica','bold');doc.setFontSize(15);doc.text(company.name||'Avenue Construction Supply GH Ltd',x,20,{maxWidth:95});doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(100,116,139);const companyLines=[company.address,company.phone,company.email,company.website].filter(Boolean);if(companyLines.length)doc.text(companyLines.join(' | '),x,27,{maxWidth:100});if(company.tax_id)doc.text(`Tax / Registration ID: ${company.tax_id}`,x,33);doc.setTextColor(15,23,42);doc.setFont('helvetica','bold');doc.setFontSize(22);doc.text('INVOICE',W-18,20,{align:'right'});doc.setFontSize(9);doc.setFont('helvetica','normal');doc.text(invoiceNumber,W-18,27,{align:'right'});doc.text(`Issued: ${fmt(new Date().toISOString().slice(0,10))}`,W-18,32,{align:'right'});doc.text(`Due: ${fmt(due)}`,W-18,37,{align:'right'});doc.setDrawColor(245,158,11);doc.setLineWidth(1);doc.line(18,43,W-18,43);
 doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text('BILL TO',18,53);doc.text('DELIVERY DETAILS',112,53);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text(delivery.customers?.name||'Customer',18,60);doc.setTextColor(100,116,139);[delivery.customers?.address,delivery.customers?.phone,delivery.customers?.email].filter(Boolean).forEach((v:any,i:number)=>doc.text(String(v),18,66+i*5,{maxWidth:80}));doc.text(`Reference: ${delivery.delivery_number}`,112,60);doc.text(`Delivery date: ${fmt(delivery.delivery_date)}`,112,65);doc.text(`Route: ${delivery.from_location||'—'} to ${delivery.to_location||'—'}`,112,70,{maxWidth:78});if(delivery.vehicles?.registration_number)doc.text(`Vehicle: ${delivery.vehicles.registration_number}`,112,75);if(delivery.profiles?.full_name)doc.text(`Driver: ${delivery.profiles.full_name}`,112,80);
 autoTable(doc,{startY:91,margin:{left:18,right:18},head:[['Description','Route','Qty','Amount']],body:[[delivery.description||'Transport / delivery service',`${delivery.from_location||'—'} → ${delivery.to_location||'—'}`,'1',ghs(amount)]],headStyles:{fillColor:[15,23,42],textColor:[255,255,255]},styles:{fontSize:9,cellPadding:4},columnStyles:{0:{cellWidth:72},1:{cellWidth:59},2:{cellWidth:14,halign:'center'},3:{cellWidth:30,halign:'right'}}});let y=(doc as any).lastAutoTable.finalY+10;doc.setFontSize(9);doc.setTextColor(100,116,139);doc.text('Subtotal',137,y);doc.text(ghs(amount),W-18,y,{align:'right'});doc.text('Tax',137,y+6);doc.text(ghs(0),W-18,y+6,{align:'right'});doc.setDrawColor(203,213,225);doc.line(137,y+10,W-18,y+10);doc.setTextColor(15,23,42);doc.setFont('helvetica','bold');doc.setFontSize(13);doc.text('TOTAL',137,y+18);doc.text(ghs(amount),W-18,y+18,{align:'right'});y=Math.min(y+36,H-66);doc.setFontSize(10);doc.text('TERMS & CONDITIONS',18,y);doc.setFont('helvetica','normal');doc.setTextColor(100,116,139);doc.setFontSize(8);doc.text(doc.splitTextToSize(terms,W-36),18,y+6);doc.setDrawColor(226,232,240);doc.line(18,H-24,W-18,H-24);doc.setFontSize(7.5);doc.text([company.trading_name||company.name,company.phone,company.email,company.website].filter(Boolean).join(' | '),18,H-17,{maxWidth:145});doc.text('Generated by ACS Truck Operations',W-18,H-17,{align:'right'});
 await supabase.from('invoices').upsert({invoice_number:invoiceNumber,delivery_id:delivery.id,customer_id:delivery.customer_id,issue_date:new Date().toISOString().slice(0,10),due_date:due,status:'issued',subtotal:amount,tax_amount:0,notes:terms},{onConflict:'invoice_number'});doc.save(`${invoiceNumber.replace(/[^A-Za-z0-9_-]/g,'_')}.pdf`)}
 return createPortal(<button className="primary v12-invoice-button" onClick={generate}><FileText size={16}/>Generate professional PDF</button>,modal)
}
