import {FormEvent,useEffect,useState} from 'react';
import {GitMerge,Plus,Save,Upload,X} from 'lucide-react';
import {createPortal} from 'react-dom';
import {supabase} from './lib/supabase';
import './v12-refinements.css';

type Profile={id:string;role:string};
type Quick='customer'|'vendor'|'vehicle'|null;
const safe=(n:string)=>n.replace(/[^a-zA-Z0-9._-]/g,'_');

export default function OperationalRefinementsV12({profile}:{profile:Profile}){
 const[page,setPage]=useState(''),[main,setMain]=useState<HTMLElement|null>(null),[modal,setModal]=useState<HTMLElement|null>(null),[modalTitle,setModalTitle]=useState(''),[quick,setQuick]=useState<Quick>(null),[vehicles,setVehicles]=useState<any[]>([]),[selected,setSelected]=useState<Set<string>>(new Set()),[target,setTarget]=useState(''),[status,setStatus]=useState(''),[files,setFiles]=useState<File[]>([]),[notice,setNotice]=useState('');
 useEffect(()=>{const detect=()=>{const m=document.querySelector('.prod-main') as HTMLElement|null;setMain(m);setPage(m?.querySelector('.prod-head h1')?.textContent?.trim()||'');const box=document.querySelector('.prod-modal') as HTMLElement|null;setModal(box);setModalTitle(box?.querySelector('header h2')?.textContent?.trim()||'');if(!box){setFiles([]);setQuick(null)}};detect();const ob=new MutationObserver(detect);ob.observe(document.body,{subtree:true,childList:true,characterData:true});return()=>ob.disconnect()},[]);
 useEffect(()=>{if(page!=='Fleet')return;loadVehicles()},[page]);
 async function loadVehicles(){const{data}=await supabase.from('vehicles').select('*').is('archived_at',null).order('registration_number');setVehicles(data||[])}
 const flash=(m:string)=>{setNotice(m);setTimeout(()=>setNotice(''),2500)};
 function toggle(id:string){const n=new Set(selected);n.has(id)?n.delete(id):n.add(id);setSelected(n)}
 async function merge(){if(profile.role!=='admin'||selected.size<2||!target)return alert('Select at least two vehicles and choose the correct target vehicle.');if(!selected.has(target))return alert('The target must be one of the selected vehicles.');const sources=[...selected].filter(x=>x!==target);const t=vehicles.find(v=>v.id===target);if(!confirm(`Merge ${sources.length} vehicle record(s) into ${t?.registration_number}? All linked deliveries, transactions, fuel and maintenance will move to the target. Source records will be archived.`))return;for(const table of ['deliveries','transactions','fuel_logs','maintenance_records','vehicle_issue_reports']){const{error}=await supabase.from(table).update({vehicle_id:target}).in('vehicle_id',sources);if(error)return alert(`${table}: ${error.message}`)}const{error}=await supabase.from('vehicles').update({archived_at:new Date().toISOString(),archived_by:profile.id,status:'inactive'}).in('id',sources);if(error)return alert(error.message);setSelected(new Set());setTarget('');flash('Vehicles merged successfully');loadVehicles();location.reload()}
 async function bulkStatus(){if(!selected.size||!status)return;const{error}=await supabase.from('vehicles').update({status}).in('id',[...selected]);if(error)return alert(error.message);flash(`Updated ${selected.size} vehicle(s)`);setSelected(new Set());setStatus('');loadVehicles();location.reload()}
 const supportsDocs=/delivery|income entry|expense entry|fuel|maintenance/i.test(modalTitle);
 async function quickSave(e:FormEvent){e.preventDefault();const form=e.currentTarget as HTMLFormElement,fd=new FormData(form);let table='',payload:any={},label='',selector='';if(quick==='customer'){table='customers';payload={name:fd.get('name'),phone:fd.get('phone')||null,email:fd.get('email')||null,address:fd.get('address')||null,active:true};label=String(fd.get('name'));selector='Customer'}else if(quick==='vendor'){table='vendors';payload={name:fd.get('name'),phone:fd.get('phone')||null,email:fd.get('email')||null,address:fd.get('address')||null,active:true};label=String(fd.get('name'));selector='Vendor'}else{table='vehicles';payload={registration_number:String(fd.get('name')).toUpperCase(),status:'active',current_odometer:0};label=String(fd.get('name')).toUpperCase();selector='Vehicle'}const{data,error}=await supabase.from(table).insert(payload).select('id').single();if(error)return alert(error.message);const labels=[...document.querySelectorAll('.prod-modal label')] as HTMLLabelElement[];const field=labels.find(l=>l.textContent?.trim().startsWith(selector));const select=field?.querySelector('select');if(select&&data?.id){const op=document.createElement('option');op.value=data.id;op.textContent=label;select.appendChild(op);select.value=data.id;select.dispatchEvent(new Event('change',{bubbles:true}))}setQuick(null);flash(`${selector} created and selected`)}
 useEffect(()=>{if(!modal||!files.length||!supportsDocs)return;const form=modal.querySelector('form');if(!form)return;const handler=()=>{const title=modalTitle;const reference=(modal.querySelector('label')?.querySelector('input') as HTMLInputElement|null)?.value;const snap=[...files];setTimeout(async()=>{let type='',row:any=null;if(/delivery/i.test(title)){type='delivery';const q=await supabase.from('deliveries').select('id').eq('delivery_number',reference||'').order('created_at',{ascending:false}).limit(1).maybeSingle();row=q.data}else if(/income entry|expense entry/i.test(title)){type='transaction';const q=await supabase.from('transactions').select('id').eq('transaction_number',reference||'').order('created_at',{ascending:false}).limit(1).maybeSingle();row=q.data}else if(/fuel/i.test(title)){type='fuel';const q=await supabase.from('fuel_logs').select('id').eq('created_by',profile.id).order('created_at',{ascending:false}).limit(1).maybeSingle();row=q.data}else if(/maintenance/i.test(title)){type='maintenance';const q=await supabase.from('maintenance_records').select('id').eq('created_by',profile.id).order('created_at',{ascending:false}).limit(1).maybeSingle();row=q.data}if(!row?.id)return;for(const file of snap){const path=`${profile.id}/${type}/${row.id}/${Date.now()}-${safe(file.name)}`;const up=await supabase.storage.from('truck-documents').upload(path,file,{contentType:file.type});if(up.error)continue;await supabase.from('documents').insert({entity_type:type,entity_id:row.id,bucket:'truck-documents',path,original_name:file.name,mime_type:file.type,size_bytes:file.size,uploaded_by:profile.id})}},900)};form.addEventListener('submit',handler,{once:true});return()=>form.removeEventListener('submit',handler)},[modal,files,modalTitle,supportsDocs,profile.id]);
 return <>{notice&&<div className="prod-toast">{notice}</div>}{page==='Fleet'&&main&&profile.role==='admin'&&createPortal(<section className="v12-merge-panel"><div className="v12-merge-head"><div><b>Fleet bulk tools</b><small>Select vehicles to bulk-update or merge duplicate registrations.</small></div><GitMerge size={20}/></div><div className="v12-fleet-select">{vehicles.map(v=><label key={v.id}><input type="checkbox" checked={selected.has(v.id)} onChange={()=>toggle(v.id)}/><span>{v.registration_number}</span></label>)}</div>{selected.size>0&&<div className="v12-compact-tools"><label>Bulk status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Select</option><option value="active">Active</option><option value="maintenance">Maintenance</option><option value="inactive">Inactive</option></select></label><button onClick={bulkStatus} disabled={!status}><Save size={15}/>Bulk edit {selected.size}</button>{selected.size>=2&&<><label>Merge into<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Choose correct vehicle</option>{vehicles.filter(v=>selected.has(v.id)).map(v=><option value={v.id} key={v.id}>{v.registration_number}</option>)}</select></label><button className="danger" onClick={merge} disabled={!target}><GitMerge size={15}/>Merge selected</button></>}</div>}</section>,main)}{modal&&createPortal(<div className="v12-modal-assist">{/(delivery|income entry|expense entry)/i.test(modalTitle)&&<button type="button" onClick={()=>setQuick('customer')}><Plus size={14}/>New customer</button>}{/(income entry|expense entry|maintenance)/i.test(modalTitle)&&<button type="button" onClick={()=>setQuick('vendor')}><Plus size={14}/>New vendor</button>}{/(delivery|income entry|expense entry|fuel|maintenance)/i.test(modalTitle)&&<button type="button" onClick={()=>setQuick('vehicle')}><Plus size={14}/>New vehicle</button>}{supportsDocs&&<label className="v12-attach"><Upload size={14}/>{files.length?`${files.length} file(s) ready`:'Attach receipt / invoice'}<input type="file" multiple accept="image/*,application/pdf" onChange={e=>setFiles([...Array.from(e.target.files||[])])}/></label>}</div>,modal)}{quick&&modal&&createPortal(<div className="v12-quick-back"><form onSubmit={quickSave} className="v12-quick-form"><header><b>New {quick}</b><button type="button" onClick={()=>setQuick(null)}><X size={17}/></button></header><label>{quick==='vehicle'?'Registration number':'Name'}<input name="name" required autoFocus/></label>{quick!=='vehicle'&&<><label>Phone<input name="phone"/></label><label>Email<input name="email" type="email"/></label><label>Address<input name="address"/></label></>}<button className="primary"><Save size={15}/>Create & select</button></form></div>,document.body)}</>}
