import {useEffect,useState} from 'react';
import {Download,RefreshCw,WifiOff,X} from 'lucide-react';
import './v13/v16.css';
const APP_VERSION='1.6.0';
type InstallPromptEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:'accepted'|'dismissed'}>};
type Release={version:string;released_at?:string;title?:string;summary?:string;changes?:string[]};
export default function PWAControls(){const[installEvent,setInstallEvent]=useState<InstallPromptEvent|null>(null),[installed,setInstalled]=useState(false),[online,setOnline]=useState(navigator.onLine),[updateReady,setUpdateReady]=useState(false),[iosHelp,setIosHelp]=useState(false),[release,setRelease]=useState<Release|null>(null),[showRelease,setShowRelease]=useState(false),[deferred,setDeferred]=useState(false);
async function getRelease(){try{const r=await fetch(`/release.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)return null;const x=await r.json() as Release;setRelease(x);return x}catch{return null}}
useEffect(()=>{const standalone=window.matchMedia('(display-mode: standalone)').matches||(navigator as any).standalone===true;setInstalled(standalone);getRelease().then(r=>{if(!r||r.version!==APP_VERSION)return;const seen=localStorage.getItem('acs-truck:last-seen-release');if(seen!==APP_VERSION)setShowRelease(true);localStorage.setItem('acs-truck:last-seen-release',APP_VERSION)});const before=(e:Event)=>{e.preventDefault();setInstallEvent(e as InstallPromptEvent)};const appInstalled=()=>{setInstalled(true);setInstallEvent(null)};const on=()=>setOnline(true);const off=()=>setOnline(false);const upd=()=>{setUpdateReady(true);setDeferred(false);getRelease()};window.addEventListener('beforeinstallprompt',before);window.addEventListener('appinstalled',appInstalled);window.addEventListener('online',on);window.addEventListener('offline',off);window.addEventListener('acs-pwa-update',upd);return()=>{window.removeEventListener('beforeinstallprompt',before);window.removeEventListener('appinstalled',appInstalled);window.removeEventListener('online',on);window.removeEventListener('offline',off);window.removeEventListener('acs-pwa-update',upd)}},[]);
async function install(){if(installEvent){await installEvent.prompt();const choice=await installEvent.userChoice;if(choice.outcome==='accepted')setInstallEvent(null);return}if(/iphone|ipad|ipod/i.test(navigator.userAgent))setIosHelp(true)}
async function update(){const fn=(window as any).__ACS_UPDATE_SW__;if(typeof fn==='function'){await fn(true);return}window.location.reload()}
function later(){setDeferred(true)}function details(){setShowRelease(true)}
return <><span className="pwa-version" title="ACS Truck Operations release version">v{APP_VERSION}</span>{!online&&<div className="pwa-offline"><WifiOff size={15}/>Offline mode — saved pages remain available; new server changes require connectivity.</div>}{updateReady&&!deferred&&<div className="v16-update-toast"><span><b>ACS Truck update available</b><small>{release?.version?`Version ${release.version} · ${release.title||'New improvements available'}`:'A newer version is ready.'}</small></span><button className="later" onClick={later}>Later</button><button className="now" onClick={update}><RefreshCw size={14}/> Update now</button><button className="v16-release-link" onClick={details}>What changed?</button></div>}{updateReady&&deferred&&<button className="pwa-install" onClick={()=>setDeferred(false)}><RefreshCw size={16}/>Update available</button>}{!installed&&(installEvent||/iphone|ipad|ipod/i.test(navigator.userAgent))&&<button className="pwa-install" onClick={install}><Download size={17}/>Install ACS Truck</button>}{iosHelp&&<div className="pwa-help"><button onClick={()=>setIosHelp(false)} aria-label="Close"><X size={18}/></button><b>Install ACS Truck</b><p>In Safari, tap <strong>Share</strong>, then choose <strong>Add to Home Screen</strong>.</p></div>}{showRelease&&<div className="v16-release-overlay" onClick={()=>setShowRelease(false)}><section className="v16-release" onClick={e=>e.stopPropagation()}><header><div><small>{release?.version?`VERSION ${release.version}`:'ACS TRUCK UPDATE'}</small><h2>{release?.title||'What changed'}</h2></div><button onClick={()=>setShowRelease(false)} aria-label="Close"><X size={19}/></button></header>{release?.summary&&<p>{release.summary}</p>}<ul>{(release?.changes||['Performance, reliability and workflow improvements.']).map((x,i)=><li key={i}>{x}</li>)}</ul><div className="v16-release-actions">{updateReady&&<button className="primary" onClick={update}><RefreshCw size={15}/> Update now</button>}<button onClick={()=>setShowRelease(false)}>{updateReady?'Later':'Close'}</button></div></section></div>}</>}
