import {useEffect,useState} from 'react';
import {Download,RefreshCw,WifiOff,X} from 'lucide-react';

const APP_VERSION='1.3.0';
type InstallPromptEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:'accepted'|'dismissed'}>};

export default function PWAControls(){const[installEvent,setInstallEvent]=useState<InstallPromptEvent|null>(null),[installed,setInstalled]=useState(false),[online,setOnline]=useState(navigator.onLine),[updateReady,setUpdateReady]=useState(false),[iosHelp,setIosHelp]=useState(false);
useEffect(()=>{const standalone=window.matchMedia('(display-mode: standalone)').matches||(navigator as any).standalone===true;setInstalled(standalone);const before=(e:Event)=>{e.preventDefault();setInstallEvent(e as InstallPromptEvent)};const appInstalled=()=>{setInstalled(true);setInstallEvent(null)};const on=()=>setOnline(true);const off=()=>setOnline(false);const upd=()=>setUpdateReady(true);window.addEventListener('beforeinstallprompt',before);window.addEventListener('appinstalled',appInstalled);window.addEventListener('online',on);window.addEventListener('offline',off);window.addEventListener('acs-pwa-update',upd);return()=>{window.removeEventListener('beforeinstallprompt',before);window.removeEventListener('appinstalled',appInstalled);window.removeEventListener('online',on);window.removeEventListener('offline',off);window.removeEventListener('acs-pwa-update',upd)}},[]);
async function install(){if(installEvent){await installEvent.prompt();const choice=await installEvent.userChoice;if(choice.outcome==='accepted')setInstallEvent(null);return}const isiOS=/iphone|ipad|ipod/i.test(navigator.userAgent);if(isiOS)setIosHelp(true)}
async function update(){const fn=(window as any).__ACS_UPDATE_SW__;if(typeof fn==='function')await fn(true);window.location.reload()}
return <><span className="pwa-version" title="ACS Truck Operations release version">v{APP_VERSION}</span>{!online&&<div className="pwa-offline"><WifiOff size={15}/>Offline mode — saved pages remain available; new server changes require connectivity.</div>}{updateReady&&<div className="pwa-update"><span>ACS Truck update detected. It will activate automatically.</span><button onClick={update}><RefreshCw size={15}/>Reload now</button></div>}{!installed&&(installEvent||/iphone|ipad|ipod/i.test(navigator.userAgent))&&<button className="pwa-install" onClick={install}><Download size={17}/>Install ACS Truck</button>}{iosHelp&&<div className="pwa-help"><button onClick={()=>setIosHelp(false)} aria-label="Close"><X size={18}/></button><b>Install ACS Truck</b><p>In Safari, tap <strong>Share</strong>, then choose <strong>Add to Home Screen</strong>.</p></div>}</>}
