import {useEffect,useMemo,useState} from 'react';
import {FileText} from 'lucide-react';
import {jsPDF} from 'jspdf';
import autoTable from 'jspdf-autotable';
import {createPortal} from 'react-dom';
import {supabase} from './lib/supabase';
import './v12-refinements.css';

type Period='day'|'week'|'month'|'quarter'|'half'|'year'|'custom';
const today=()=>new Date().toISOString().slice(0,10);
const fmt=(v:any)=>{if(!v)return '—';const d=v instanceof Date?v:new Date(`${String(v).slice(0,10)}T00:00:00`);return d.toLocaleDateString('en-GH',{day:'2-digit',month:'short',year:'numeric'})};
const ghs=(n:any)=>`GHS ${Number(n||0).toLocaleString('en-GH',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const clean=(v:any)=>String(v??'—').replace(/_/g,' ');
function presetBounds(k:Exclude<Period,'custom'>,anchor:string){const d=new Date(`${anchor}T00:00:00`);let s=new Date(d),e=new Date(d);if(k==='week'){const n=(d.getDay()+6)%7;s.setDate(d.getDate()-n);e=new Date(s);e.setDate(s.getDate()+6)}else if(k==='month'){s=new Date(d.getFullYear(),d.getMonth(),1);e=new Date(d.getFullYear(),d.getMonth()+1,0)}else if(k==='quarter'){const q=Math.floor(d.getMonth()/3)*3;s=new Date(d.getFullYear(),q,1);e=new Date(d.getFullYear(),q+3,0)}else if(k==='half'){const h=d.getMonth()<6?0:6;s=new Date(d.getFullYear(),h,1);e=new Date(d.getFullYear(),h+6,0)}else if(k==='year'){s=new Date(d.getFullYear(),0,1);e=new Date(d.getFullYear(),11,31)}return{start:s,end:e}}
const prior=(b:{start:Date,end:Date})=>{const days=Math.round((b.end.getTime()-b.start.getTime())/86400000)+1,e=new Date(b.start);e.setDate(e.getDate()-1);const s=new Date(e);s.setDate(e.getDate()-days+1);return{start:s,end:e}};
const inRange=(v:any,b:{start:Date,end:Date})=>{if(!v)return false;const d=new Date(`${String(v).slice(0,10)}T00:00:00`);return d>=b.start&&d<=b.end};
async function imageData(path?:string){if(!path||path.toLowerCase().endsWith('.svg'))return null;try{const {data}=await supabase.storage.from('company-assets').createSignedUrl(path,300);if(!data?.signedUrl)return null;const blob=await fetch(data.signedUrl).then(r=>r.blob());return await new Promise<string>((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(String(fr.result));fr.onerror=rej;fr.readAsDataURL(blob)})}catch{return null}}

export default function ReportsV12(){
 const[active,setActive]=useState(false),[host,setHost]=useState<HTMLElement|null>(null),[period,setPeriod]=useState<Period>('year'),[anchor,setAnchor]=useState(today()),[from,setFrom]=useState(`${new Date().getFullYear()}-01-01`),[to,setTo]=useState(today()),[tx,setTx]=useState<any[]>([]),[company,setCompany]=useState<any>({});
 useEffect(()=>{const detect=()=>{const main=document.querySelector('.prod-main') as HTMLElement|null;const on=main?.querySelector('.prod-head h1')?.textContent?.trim()==='Reports';setHost(main);setActive(on);main?.classList.toggle('v12-reports-managed',on)};detect();const m=new MutationObserver(detect);m.observe(document.body,{childList:true,subtree:true,characterData:true});return()=>m.disconnect()},[]);
 useEffect(()=>{if(!active)return;Promise.all([supabase.from('transactions').select('transaction_date,direction,amount,paid_amount,description,transaction_categories(name)').is('archived_at',null).order('transaction_date'),supabase.from('app_settings').select('value').eq('key','company').maybeSingle()]).then(([a,b])=>{setTx(a.data||[]);setCompany(b.data?.value||{})})},[active]);
 const bounds=useMemo(()=>period==='custom'?{start:new Date(`${from}T00:00:00`),end:new Date(`${to}T00:00:00`)}:presetBounds(period,anchor),[period,anchor,from,to]);
 const prev=useMemo(()=>prior(bounds),[bounds.start.getTime(),bounds.end.getTime()]);
 const cur=tx.filter(t=>inRange(t.transaction_date,bounds)),old=tx.filter(t=>inRange(t.transaction_date,prev));
 const calc=(rows:any[])=>({income:rows.filter(x=>x.direction==='income').reduce((s,x)=>s+Number(x.amount||0),0),expense:rows.filter(x=>x.direction==='expense').reduce((s,x)=>s+Number(x.amount||0),0),receivables:rows.filter(x=>x.direction==='income').reduce((s,x)=>s+Math.max(0,Number(x.amount||0)-Number(x.paid_amount||0)),0)});
 const c=calc(cur),p=calc(old),net=c.income-c.expense,pnet=p.income-p.expense;
 const incomeCats=Object.values(cur.filter(x=>x.direction==='income').reduce((o:any,t:any)=>{const k=t.transaction_categories?.name||'Unclassified';o[k]=(o[k]||0)+Number(t.amount||0);return o},{})).length?Object.entries(cur.filter(x=>x.direction==='income').reduce((o:any,t:any)=>{const k=t.transaction_categories?.name||'Unclassified';o[k]=(o[k]||0)+Number(t.amount||0);return o},{})).sort((a:any,b:any)=>b[1]-a[1]):[];
 const expenseCats=Object.entries(cur.filter(x=>x.direction==='expense').reduce((o:any,t:any)=>{const k=t.transaction_categories?.name||'Unclassified';o[k]=(o[k]||0)+Number(t.amount||0);return o},{})).sort((a:any,b:any)=>b[1]-a[1]);
 const delta=(a:number,b:number)=>b===0?(a===0?'0%':'New'):`${(((a-b)/Math.abs(b))*100).toFixed(1)}%`;
 async function pdf(){const d=new jsPDF('p','mm','a4'),W=d.internal.pageSize.getWidth(),H=d.internal.pageSize.getHeight(),logo=await imageData(company.logo_path);d.setFillColor(15,23,42);d.rect(0,0,W,10,'F');let companyX=18;if(logo){try{d.addImage(logo,'PNG',18,15,24,18);companyX=48}catch{}}d.setTextColor(15,23,42);d.setFont('helvetica','bold');d.setFontSize(15);d.text(company.name||'Avenue Construction Supply GH Ltd',companyX,20,{maxWidth:92});d.setFont('helvetica','normal');d.setFontSize(8);d.setTextColor(100,116,139);const details=[company.address,company.phone,company.email,company.website].filter(Boolean);if(details.length)d.text(details.join(' | '),companyX,27,{maxWidth:100});if(company.tax_id)d.text(`Tax / Registration ID: ${company.tax_id}`,companyX,33);
 d.setTextColor(15,23,42);d.setFont('helvetica','bold');d.setFontSize(20);d.text('PROFIT & LOSS',W-18,20,{align:'right'});d.setFontSize(10);d.text('Management Report',W-18,27,{align:'right'});d.setFont('helvetica','normal');d.setFontSize(8);d.setTextColor(100,116,139);d.text(`${fmt(bounds.start)} to ${fmt(bounds.end)}`,W-18,33,{align:'right'});d.setDrawColor(245,158,11);d.setLineWidth(1);d.line(18,40,W-18,40);
 d.setFont('helvetica','bold');d.setFontSize(11);d.setTextColor(15,23,42);d.text('PERFORMANCE SUMMARY',18,49);autoTable(d,{startY:54,margin:{left:18,right:18},head:[['Metric','Current period','Previous period','Movement']],body:[['Total income',ghs(c.income),ghs(p.income),delta(c.income,p.income)],['Total expenses',ghs(c.expense),ghs(p.expense),delta(c.expense,p.expense)],['Net profit / (loss)',ghs(net),ghs(pnet),delta(net,pnet)],['Outstanding receivables',ghs(c.receivables),ghs(p.receivables),delta(c.receivables,p.receivables)]],headStyles:{fillColor:[15,23,42],textColor:[255,255,255],fontStyle:'bold'},styles:{fontSize:8.5,cellPadding:3},alternateRowStyles:{fillColor:[248,250,252]},columnStyles:{1:{halign:'right'},2:{halign:'right'},3:{halign:'right'}}});let y=(d as any).lastAutoTable.finalY+10;
 d.setFont('helvetica','bold');d.setFontSize(11);d.setTextColor(15,23,42);d.text('INCOME',18,y);autoTable(d,{startY:y+4,margin:{left:18,right:18},head:[['Income category','Amount']],body:[...incomeCats.map((x:any)=>[x[0],ghs(x[1])]),['TOTAL INCOME',ghs(c.income)]],headStyles:{fillColor:[22,101,52]},styles:{fontSize:8.5,cellPadding:3},columnStyles:{1:{halign:'right'}},didParseCell:data=>{if(data.section==='body'&&data.row.index===incomeCats.length)data.cell.styles.fontStyle='bold'}});y=(d as any).lastAutoTable.finalY+10;
 d.setFont('helvetica','bold');d.setFontSize(11);d.text('EXPENSES',18,y);autoTable(d,{startY:y+4,margin:{left:18,right:18},head:[['Expense category','Amount']],body:[...expenseCats.map((x:any)=>[x[0],ghs(x[1])]),['TOTAL EXPENSES',ghs(c.expense)],['NET PROFIT / (LOSS)',ghs(net)]],headStyles:{fillColor:[180,35,24]},styles:{fontSize:8.5,cellPadding:3},columnStyles:{1:{halign:'right'}},didParseCell:data=>{if(data.section==='body'&&data.row.index>=expenseCats.length)data.cell.styles.fontStyle='bold'}});
 const footer=()=>{const pages=(d as any).internal.getNumberOfPages();for(let i=1;i<=pages;i++){d.setPage(i);d.setDrawColor(226,232,240);d.line(18,H-20,W-18,H-20);d.setFont('helvetica','normal');d.setFontSize(7.5);d.setTextColor(100,116,139);d.text([company.trading_name||company.name||'ACS Truck Operations',company.phone,company.email].filter(Boolean).join(' | '),18,H-14,{maxWidth:130});d.text(`Page ${i} of ${pages}`,W-18,H-14,{align:'right'});d.text(`Generated ${new Date().toLocaleString('en-GH')} · ACS Truck Operations`,18,H-9)}};footer();d.save(`ACS-PnL-${from}-${to}.pdf`)}
 if(!active||!host)return null;
 return createPortal(<section className="v12-report-root"><div className="v12-report-toolbar"><div><h2>Profit & Loss</h2><p>{fmt(bounds.start)} – {fmt(bounds.end)}</p></div><select value={period} onChange={e=>setPeriod(e.target.value as Period)}><option value="day">Day</option><option value="week">Week</option><option value="month">Month</option><option value="quarter">Quarter</option><option value="half">Half year</option><option value="year">Year</option><option value="custom">Custom range</option></select>{period==='custom'?<><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} min={from} onChange={e=>setTo(e.target.value)}/></label></>:<label>Anchor date<input type="date" value={anchor} onChange={e=>setAnchor(e.target.value)}/></label>}<button className="primary" onClick={pdf}><FileText size={16}/>Download P&L PDF</button></div><div className="v12-report-cards"><article><small>Income</small><strong>{ghs(c.income)}</strong><span>Previous {ghs(p.income)} · {delta(c.income,p.income)}</span></article><article><small>Expenses</small><strong>{ghs(c.expense)}</strong><span>Previous {ghs(p.expense)} · {delta(c.expense,p.expense)}</span></article><article><small>Net profit / loss</small><strong className={net<0?'negative':''}>{ghs(net)}</strong><span>Previous {ghs(pnet)} · {delta(net,pnet)}</span></article><article><small>Receivables</small><strong>{ghs(c.receivables)}</strong><span>Previous {ghs(p.receivables)} · {delta(c.receivables,p.receivables)}</span></article></div><div className="v12-report-grid"><section><h3>Income statement</h3>{incomeCats.map((x:any)=><div key={x[0]}><span>{x[0]}</span><b>{ghs(x[1])}</b></div>)}<div className="total"><span>Total income</span><b>{ghs(c.income)}</b></div></section><section><h3>Expense statement</h3>{expenseCats.map((x:any)=><div key={x[0]}><span>{x[0]}</span><b>{ghs(x[1])}</b></div>)}<div className="total"><span>Total expenses</span><b>{ghs(c.expense)}</b></div><div className="net"><span>Net profit / loss</span><b className={net<0?'negative':''}>{ghs(net)}</b></div></section></div></section>,host)
}
