-- ACS Truck v1.6.0: in-app notification center and role-aware alerts.
alter table public.notifications add column if not exists notification_type text not null default 'info';
alter table public.notifications add column if not exists priority text not null default 'normal';
alter table public.notifications add column if not exists action_page text;
alter table public.notifications add column if not exists metadata jsonb not null default '{}'::jsonb;
do $$ begin if not exists(select 1 from pg_constraint where conname='notifications_priority_check') then alter table public.notifications add constraint notifications_priority_check check(priority in ('low','normal','high','urgent')); end if; end $$;
create index if not exists notifications_user_created_idx on public.notifications(user_id,created_at desc);
create index if not exists notifications_user_unread_idx on public.notifications(user_id,read_at) where read_at is null;

create or replace function public.notify_user(p_user uuid,p_title text,p_body text default null,p_type text default 'info',p_priority text default 'normal',p_entity_type text default null,p_entity_id uuid default null,p_action_page text default null,p_metadata jsonb default '{}'::jsonb)
returns void language plpgsql security definer set search_path=public as $$ begin if p_user is null then return; end if; insert into public.notifications(user_id,title,body,notification_type,priority,entity_type,entity_id,action_page,metadata) values(p_user,p_title,p_body,coalesce(p_type,'info'),coalesce(p_priority,'normal'),p_entity_type,p_entity_id,p_action_page,coalesce(p_metadata,'{}'::jsonb)); end $$;
create or replace function public.notify_roles(p_roles text[],p_title text,p_body text default null,p_type text default 'info',p_priority text default 'normal',p_entity_type text default null,p_entity_id uuid default null,p_action_page text default null,p_metadata jsonb default '{}'::jsonb,p_exclude uuid default null)
returns void language plpgsql security definer set search_path=public as $$ begin insert into public.notifications(user_id,title,body,notification_type,priority,entity_type,entity_id,action_page,metadata) select p.id,p_title,p_body,coalesce(p_type,'info'),coalesce(p_priority,'normal'),p_entity_type,p_entity_id,p_action_page,coalesce(p_metadata,'{}'::jsonb) from public.profiles p where p.active=true and p.role=any(p_roles) and (p_exclude is null or p.id<>p_exclude); end $$;
revoke all on function public.notify_user(uuid,text,text,text,text,text,uuid,text,jsonb) from public,anon,authenticated;
revoke all on function public.notify_roles(text[],text,text,text,text,text,uuid,text,jsonb,uuid) from public,anon,authenticated;

create or replace function public.delivery_notifications_trigger() returns trigger language plpgsql security definer set search_path=public as $$
declare drv text; cust text; begin select full_name into drv from public.profiles where id=new.driver_id; select name into cust from public.customers where id=new.customer_id;
if tg_op='INSERT' then
 if new.driver_id is not null then perform public.notify_user(new.driver_id,'New delivery assigned',coalesce(new.delivery_number,'Delivery')||' · '||coalesce(new.from_location,'—')||' → '||coalesce(new.to_location,'—'),'delivery','high','delivery',new.id,'income',jsonb_build_object('status',new.status)); end if;
 perform public.notify_roles(array['admin','operations'],'Delivery recorded',coalesce(new.delivery_number,'Delivery')||case when cust is not null then ' for '||cust else '' end,'delivery','normal','delivery',new.id,'income','{}'::jsonb,new.created_by);
elsif tg_op='UPDATE' then
 if new.driver_id is distinct from old.driver_id and new.driver_id is not null then perform public.notify_user(new.driver_id,'Delivery assigned to you',coalesce(new.delivery_number,'Delivery')||' · '||coalesce(new.from_location,'—')||' → '||coalesce(new.to_location,'—'),'delivery','high','delivery',new.id,'income',jsonb_build_object('status',new.status)); end if;
 if new.status is distinct from old.status then
  if new.driver_id is not null then perform public.notify_user(new.driver_id,'Delivery status updated',coalesce(new.delivery_number,'Delivery')||' is now '||replace(new.status,'_',' '),'delivery','normal','delivery',new.id,'income',jsonb_build_object('status',new.status)); end if;
  perform public.notify_roles(array['admin','operations'],'Delivery status: '||replace(new.status,'_',' '),coalesce(new.delivery_number,'Delivery')||case when drv is not null then ' · '||drv else '' end,'delivery',case when new.status='delivered' then 'high' else 'normal' end,'delivery',new.id,'income',jsonb_build_object('status',new.status),new.driver_id);
  if new.status='delivered' then perform public.notify_roles(array['accounts'],'Delivery completed',coalesce(new.delivery_number,'Delivery')||' is delivered. Review payment/receivable status.','finance','high','delivery',new.id,'income',jsonb_build_object('expected_income',new.expected_income,'payment_status',new.payment_status),null); end if;
 end if;
 if new.payment_status is distinct from old.payment_status then perform public.notify_roles(array['admin','accounts'],'Delivery payment updated',coalesce(new.delivery_number,'Delivery')||' · '||replace(new.payment_status,'_',' '),'finance','normal','delivery',new.id,'income',jsonb_build_object('payment_status',new.payment_status,'amount',new.expected_income),null); end if;
end if; return new; end $$;
drop trigger if exists delivery_notifications on public.deliveries; create trigger delivery_notifications after insert or update of driver_id,status,payment_status on public.deliveries for each row execute function public.delivery_notifications_trigger();

create or replace function public.transaction_notifications_trigger() returns trigger language plpgsql security definer set search_path=public as $$ declare cat text; begin select name into cat from public.transaction_categories where id=new.category_id;
if tg_op='INSERT' then if coalesce(new.source,'manual') in ('manual','api','other') then perform public.notify_roles(array['admin','accounts'],case when new.direction='income' then 'Income recorded' else 'Expense recorded' end,coalesce(cat,initcap(new.direction))||' · GHS '||to_char(coalesce(new.amount,0),'FM999G999G990D00'),'finance',case when coalesce(new.amount,0)>=5000 then 'high' else 'normal' end,'transaction',new.id,case when new.direction='income' then 'income' else 'expenses' end,jsonb_build_object('amount',new.amount,'payment_status',new.payment_status),new.created_by); end if;
elsif new.payment_status is distinct from old.payment_status then perform public.notify_roles(array['admin','accounts'],'Payment status changed',coalesce(new.transaction_number,'Transaction')||' · '||replace(new.payment_status,'_',' '),'finance','normal','transaction',new.id,case when new.direction='income' then 'income' else 'expenses' end,jsonb_build_object('amount',new.amount,'payment_status',new.payment_status),null); end if; return new; end $$;
drop trigger if exists transaction_notifications on public.transactions; create trigger transaction_notifications after insert or update of payment_status on public.transactions for each row execute function public.transaction_notifications_trigger();

create or replace function public.maintenance_notifications_trigger() returns trigger language plpgsql security definer set search_path=public as $$ declare reg text; begin select registration_number into reg from public.vehicles where id=new.vehicle_id; if tg_op='INSERT' then perform public.notify_roles(array['admin','operations','accounts'],'Maintenance recorded',coalesce(reg,'Truck')||' · '||coalesce(new.maintenance_type,'Maintenance')||' · GHS '||to_char(coalesce(new.cost,0),'FM999G999G990D00'),'maintenance',case when coalesce(new.cost,0)>=3000 then 'high' else 'normal' end,'maintenance',new.id,'expenses',jsonb_build_object('cost',new.cost,'status',new.status),new.created_by); elsif new.status is distinct from old.status then perform public.notify_roles(array['admin','operations'],'Maintenance status updated',coalesce(reg,'Truck')||' · '||replace(new.status,'_',' '),'maintenance','normal','maintenance',new.id,'expenses',jsonb_build_object('status',new.status),null); end if; return new; end $$;
drop trigger if exists maintenance_notifications on public.maintenance_records; create trigger maintenance_notifications after insert or update of status on public.maintenance_records for each row execute function public.maintenance_notifications_trigger();

create or replace function public.fuel_notifications_trigger() returns trigger language plpgsql security definer set search_path=public as $$ declare reg text; drv text; begin select registration_number into reg from public.vehicles where id=new.vehicle_id; select full_name into drv from public.profiles where id=new.driver_id; if tg_op='INSERT' then perform public.notify_roles(array['admin','operations'],'Fuel recorded',coalesce(reg,'Truck')||' · GHS '||to_char(coalesce(new.amount,0),'FM999G999G990D00')||case when new.litres is not null then ' · '||trim(to_char(new.litres,'FM999G990D00'))||' L' else '' end,'fuel','normal','fuel',new.id,'expenses',jsonb_build_object('amount',new.amount,'litres',new.litres,'driver',drv),new.created_by); perform public.notify_roles(array['accounts'],'Fuel expense recorded',coalesce(reg,'Truck')||' · GHS '||to_char(coalesce(new.amount,0),'FM999G999G990D00'),'finance','normal','fuel',new.id,'expenses',jsonb_build_object('amount',new.amount,'litres',new.litres),new.created_by); end if; return new; end $$;
drop trigger if exists fuel_notifications on public.fuel_logs; create trigger fuel_notifications after insert on public.fuel_logs for each row execute function public.fuel_notifications_trigger();

create or replace function public.profile_access_notifications_trigger() returns trigger language plpgsql security definer set search_path=public as $$ begin if tg_op='UPDATE' and (new.role,new.active,new.can_view_dashboard,new.history_months,new.default_vehicle_id) is distinct from (old.role,old.active,old.can_view_dashboard,old.history_months,old.default_vehicle_id) then perform public.notify_user(new.id,'Your access settings changed','Your ACS Truck role or access permissions were updated. Open the app to review your available areas.','access','high','profile',new.id,null,jsonb_build_object('role',new.role,'active',new.active,'dashboard',new.can_view_dashboard,'history_months',new.history_months)); end if; return new; end $$;
drop trigger if exists profile_access_notifications on public.profiles; create trigger profile_access_notifications after update of role,active,can_view_dashboard,history_months,default_vehicle_id on public.profiles for each row execute function public.profile_access_notifications_trigger();

do $$ begin if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='notifications') then alter publication supabase_realtime add table public.notifications; end if; end $$;
